In [1]:
import importlib
import datetime
import json
from pathlib import Path

import pandas as pd
import numpy as np

import lib
importlib.reload(lib)

log = lib.getLogger('yelp_dataset')
working_directory = Path().cwd()
export_directory = working_directory / 'yelp_dataset'
export_clean_directory = export_directory / 'clean'

In [2]:
path_dataset_checkin = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/yelp_academic_dataset_checkin.json'  # 287 MB

In [3]:
df_checkin = lib.read_json(path_dataset_checkin)

In [4]:
df_checkin.head()

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22
3  --7PUidqRWpRSpXebiyxTg  2011-02-15 17:12:00, 2011-07-28 02:46:10, 2012...
4  --7jw19RH9JKXgFohspgQw  2014-04-21 20:42:11, 2014-04-28 21:04:46, 2014...

In [6]:
df_checkin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [5]:
lib.info(df_checkin)

PortfolioLogger.lib.tools: INFO: Null INFO ********************************************
PortfolioLogger.lib.tools: INFO: 0/2 columns contain null values
PortfolioLogger.lib.tools: INFO: 0 total null values
PortfolioLogger.lib.tools: INFO: 0 row(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: 0 column(s) contain ALL null values
PortfolioLogger.lib.tools: INFO: Risk Rate INFO ***************************************
PortfolioLogger.lib.tools: INFO:
            error_percent error_count
business_id         0.00%           0
date                0.00%           0
PortfolioLogger.lib.tools: INFO: Data Types INFO **************************************
PortfolioLogger.lib.tools: INFO:
            has_different_types has_<NA>
business_id               False        0
date                      False        0
PortfolioLogger.lib.tools: INFO:  *****************************************************
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:696: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result = result.fillna(0)
PortfolioLogger.lib.tools: INFO:
               business_id    date
<class 'str'>       131930  131930
PortfolioLogger.lib.tools: INFO: Values Counter INFO **********************************
PortfolioLogger.lib.tools: INFO: Columns ['business_id', 'date'] exceeded maximum values of 20
PortfolioLogger.lib.performance: INFO: <function info at 0x10d090ae0> took 1.258 secs to complete.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131930 entries, 0 to 131929
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  131930 non-null  object
 1   date         131930 non-null  object
dtypes: object(2)
memory usage: 2.0+ MB

In [7]:
df_checkin.loc[0, 'date']

'2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020-07-24 22:42:27, 2020-10-24 21:36:13, 2020-12-09 21:23:33, 2021-01-20 17:34:57, 2021-04-30 21:02:03, 2021-05-25 21:16:54, 2021-08-06 21:08:08, 2021-10-02 15:15:42, 2021-11-11 16:23:50'

In [8]:
checkin_dict = {}
rows_data = []
for index, row in df_checkin.iterrows():
    for timestamp in row['date'].split(', '):
        rows_data.append({'business_id': row['business_id'], 'date': timestamp})
df_checkin_cleaned_CLEANED = pd.DataFrame(rows_data)
df_checkin_cleaned_CLEANED.head()

              business_id                 date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56
1  ---kPU91CF4Lq2-WlRu9Lw  2020-06-02 22:18:06
2  ---kPU91CF4Lq2-WlRu9Lw  2020-07-24 22:42:27
3  ---kPU91CF4Lq2-WlRu9Lw  2020-10-24 21:36:13
4  ---kPU91CF4Lq2-WlRu9Lw  2020-12-09 21:23:33

In [9]:
df_checkin_cleaned_CLEANED['date'] = pd.to_datetime(df_checkin_cleaned_CLEANED['date'])

In [10]:
df_checkin_cleaned_CLEANED.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13356875 entries, 0 to 13356874
Data columns (total 2 columns):
 #   Column       Dtype
---  ------       -----
 0   business_id  object
 1   date         datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 203.8+ MB

In [11]:
lib.export_data(export_clean_directory / 'yelp_checkin.csv', df_checkin_cleaned_CLEANED)

PortfolioLogger.lib.tools: INFO: Exporting 26713750 elements (1006.31 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_checkin_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10d091940> took 29.754 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/yelp/yelp_dataset/clean/yelp_checkin_CLEAN.csv')