In [1]:
import pandas as pd
import importlib

import lib

importlib.reload(lib)

name = 'layoffs'
log = lib.logger.getLogger(name)

# Read dataset

In [2]:
filename = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/layoffs/layoffs.csv'
df = lib.read_data(filename, sep=',')

Encoding: utf-8
Stripping whitespaces from layoffs.csv

## Getting the general info to see what we're working with

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2361 entries, 0 to 2360
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   company                2361 non-null   object
 1   location               2361 non-null   object
 2   industry               2357 non-null   object
 3   total_laid_off         1621 non-null   float64
 4   percentage_laid_off    1576 non-null   float64
 5   date                   2360 non-null   object
 6   stage                  2355 non-null   object
 7   country                2361 non-null   object
 8   funds_raised_millions  2152 non-null   float64
dtypes: float64(3), object(6)
memory usage: 166.1+ KB

In [4]:
lib.tools.info(df)

INFO
-------------------------------------------------------------------------------
Null INFO
6/9 columns contain null values
1745 total null values
-------------------------------------------------------------------------------
Column "company" has no null values
Column "location" has no null values
Column "country" has no null values
Column "industry" has 4 null values
Column "total_laid_off" has 740 null values
Column "percentage_laid_off" has 785 null values
Column "date" has 1 null values
Column "stage" has 6 null values
Column "funds_raised_millions" has 209 null values

Risk Rate ---------------------------------------------------------------------
company                  0.000000
location                 0.000000
industry                 0.001694
total_laid_off           0.313427
percentage_laid_off      0.332486
date                     0.000424
stage                    0.002541
country                  0.000000
funds_raised_millions    0.088522
dtype: float64
Column Risk Rates
company                  0.000000
location                 0.000000
industry                 0.001694
total_laid_off           0.313427
percentage_laid_off      0.332486
date                     0.000424
stage                    0.002541
country                  0.000000
funds_raised_millions    0.088522
dtype: float64
-------------------------------------------------------------------------------
Data Types Info
                      has_different_types has_<NA>
company                             False        0
location                            False        0
industry                            False        4
total_laid_off                      False      740
percentage_laid_off                 False      785
date                                False        1
stage                               False        6
country                             False        0
funds_raised_millions               False      209
-------------------------------------------------------------------------------
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:573: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  result = result.fillna(0)
                 company  location  industry  total_laid_off  \
<NA>                   0         0         4             740
<class 'float'>        0         0         0            1621
<class 'str'>       2361      2361      2357               0

                 percentage_laid_off  date  stage  country  \
<NA>                             785     1      6        0
<class 'float'>                 1576     0      0        0
<class 'str'>                      0  2360   2355     2361

                 funds_raised_millions
<NA>                               209
<class 'float'>                   2152
<class 'str'>                        0
-------------------------------------------------------------------------------
Values Counter
company: <object> BEGIN
company: Has more than 20 values (1890 values)

location: <object> BEGIN
location: Has more than 20 values (191 values)

industry: <object> BEGIN
industry: Has more than 20 values (33 values)

total_laid_off: <float64> BEGIN
total_laid_off: Has more than 20 values (1025 values)

percentage_laid_off: <float64> BEGIN
percentage_laid_off: Has more than 20 values (858 values)

date: <object> BEGIN
date: Has more than 20 values (484 values)

stage: <object> BEGIN
	Post-IPO: 428
	Series B: 305
	Unknown: 393
	Acquired: 172
	Series F: 65
	Series E: 125
	Series A: 177
	Subsidiary: 5
	Series C: 303
	Series G: 15
	Series D: 225
	Seed: 65
	Series H: 24
	Private Equity: 38
	Series J: 8
	nan: 6
	Series I: 7
stage: <object> END

country: <object> BEGIN
country: Has more than 20 values (60 values)

funds_raised_millions: <float64> BEGIN
funds_raised_millions: Has more than 20 values (847 values)

## Creating a backup

In [5]:
df_cp1 = df.copy()

# Starting Cleaning Process

## Checking for columns that have multiple data types

In [6]:
lib.tools.has_different_dtypes(df_cp1)

                      has_different_types has_<NA>
company                             False        0
location                            False        0
industry                            False        4
total_laid_off                      False      740
percentage_laid_off                 False      785
date                                False        1
stage                               False        6
country                             False        0
funds_raised_millions               False      209

### No different data types found, moving onto cleaning null values

## Cleaning Null values

In [7]:
importlib.reload(lib)
has_null, all_null_rows, all_null_columns = lib.null_info(df_cp1)

6/9 columns contain null values
1745 total null values
-------------------------------------------------------------------------------
Column "company" has no null values
Column "location" has no null values
Column "country" has no null values
Column "industry" has 4 null values
Column "total_laid_off" has 740 null values
Column "percentage_laid_off" has 785 null values
Column "date" has 1 null values
Column "stage" has 6 null values
Column "funds_raised_millions" has 209 null values

Risk Rate ---------------------------------------------------------------------
company                  0.000000
location                 0.000000
industry                 0.001694
total_laid_off           0.313427
percentage_laid_off      0.332486
date                     0.000424
stage                    0.002541
country                  0.000000
funds_raised_millions    0.088522
dtype: float64

In [8]:
log.info(has_null.columns)
has_null

Index(['industry', 'total_laid_off', 'percentage_laid_off', 'date', 'stage',
       'funds_raised_millions'],
      dtype='object')

,industry,total_laid_off,percentage_laid_off,date,stage,funds_raised_millions
2,Retail,400.0,NaN,3/6/2023,Series B,16.0
3,Education,120.0,NaN,3/6/2023,Unknown,631.0
6,Real Estate,100.0,NaN,3/3/2023,Unknown,59.0
7,Marketing,63.0,NaN,3/3/2023,Acquired,152.0
8,NaN,30.0,NaN,3/3/2023,Post-IPO,6400.0
...,...,...,...,...,...,...
2347,Retail,NaN,NaN,3/19/2020,Acquired,0.0
2351,Travel,NaN,1.00,3/16/2020,Seed,5.1
2355,Logistics,75.0,NaN,3/11/2020,Series A,12.0
2356,Other,500.0,0.14,NaN,Post-IPO,NaN
2359,Retail,NaN,NaN,9/14/2021,Post-IPO,339.0

## Found columns that have null values ['industry', 'total_laid_off', 'percentage_laid_off', 'date', 'stage', 'funds_raised_millions']

In [9]:
filler_values = {}

In [10]:
df_cp1['industry'].unique()

array(['Other', 'Media', 'Retail', 'Education', 'Real Estate',
       'Transportation', 'Marketing', nan, 'Healthcare', 'Security',
       'Food', 'Fitness', 'Consumer', 'Logistics', 'HR', 'Support',
       'Travel', 'Crypto', 'Finance', 'Data', 'Sales', 'Infrastructure',
       'Hardware', 'Product', 'Construction', 'Legal', 'Energy',
       'Manufacturing', 'Recruiting', 'Aerospace', 'Crypto Currency',
       'Fin-Tech', 'CryptoCurrency'], dtype=object)

In [11]:
df_cp1['total_laid_off'].unique()

array([5.000e+02, 4.750e+02, 4.000e+02, 1.200e+02, 3.400e+02, 2.300e+02,
       1.000e+02, 6.300e+01, 3.000e+01,       nan, 1.770e+02, 7.900e+01,
       5.000e+01, 1.200e+01, 3.550e+02, 3.000e+02, 2.090e+02, 2.000e+02,
       8.000e+01, 2.850e+02, 1.300e+02, 7.500e+01, 7.000e+01, 1.900e+01,
       4.000e+01, 8.500e+03, 2.200e+02, 5.900e+01, 2.600e+01, 2.400e+01,
       1.500e+02, 6.900e+01, 1.860e+02, 8.500e+01, 1.700e+01, 8.000e+00,
       1.290e+02, 6.800e+02, 3.700e+02, 2.210e+02, 2.100e+02, 2.080e+02,
       2.800e+01, 3.710e+02, 1.500e+03, 1.410e+02, 9.400e+01, 5.400e+01,
       2.200e+01, 3.600e+02, 1.600e+03, 6.490e+02, 3.500e+02, 2.150e+02,
       1.550e+02, 1.260e+02, 1.190e+02, 6.600e+01, 3.100e+01, 5.300e+02,
       1.300e+03, 2.120e+02, 8.300e+01, 2.700e+01, 6.650e+03, 2.000e+01,
       9.000e+01, 8.900e+01, 2.500e+02, 1.270e+02, 1.250e+02, 3.800e+01,
       3.250e+02, 1.400e+02, 1.210e+02, 6.000e+01, 5.600e+01, 4.400e+01,
       3.400e+01, 2.000e+03, 9.600e+02, 5.250e+02, 3.650e+02, 6.000e+03,
       8.000e+02, 3.430e+02, 1.560e+02, 6.500e+01, 1.380e+02, 7.300e+01,
       2.900e+01, 2.100e+01, 3.000e+03, 3.900e+03, 3.300e+02, 2.450e+02,
       1.600e+01, 1.100e+01, 6.000e+02, 1.200e+04, 1.750e+03, 3.800e+02,
       9.200e+01, 4.700e+01, 1.100e+03, 1.150e+02, 6.200e+01, 4.600e+01,
       1.000e+04, 4.500e+02, 2.750e+02, 1.370e+02, 1.090e+02, 2.840e+02,
       2.060e+02, 1.420e+02, 1.100e+02, 9.000e+02, 2.250e+02, 1.110e+02,
       1.040e+02, 6.400e+01, 5.500e+01, 6.400e+02, 2.700e+02, 1.230e+02,
       4.100e+01, 3.300e+01, 9.500e+02, 7.600e+01, 3.150e+02, 4.300e+01,
       3.880e+02, 2.500e+01, 8.000e+03, 7.000e+02, 9.900e+01, 9.300e+01,
       1.530e+02, 1.800e+01, 1.800e+02, 7.200e+01, 1.600e+02, 9.500e+01,
       7.800e+01, 3.290e+02, 3.500e+01, 1.130e+02, 2.540e+02, 1.980e+02,
       3.850e+02, 3.120e+02, 2.600e+02, 2.370e+02, 2.350e+02, 5.150e+02,
       2.010e+02, 1.750e+02, 3.200e+01, 1.300e+01, 8.800e+01, 4.800e+01,
       3.700e+01, 1.250e+03, 1.580e+02, 1.340e+02, 5.300e+01, 4.500e+01,
       1.000e+01, 6.700e+01, 2.510e+02, 1.050e+02, 5.700e+01, 5.800e+01,
       1.500e+01, 9.000e+00, 4.100e+03, 2.110e+02, 2.410e+02, 1.700e+02,
       7.100e+01, 1.430e+02, 1.240e+02, 5.100e+01, 1.100e+04, 8.620e+02,
       1.440e+02, 3.600e+01, 1.000e+03, 1.900e+02, 3.700e+03, 5.500e+02,
       2.590e+02, 2.260e+02, 2.300e+01, 8.400e+01, 1.730e+02, 4.000e+03,
       2.270e+02, 3.780e+02, 2.500e+03, 1.360e+02, 6.110e+02, 9.600e+01,
       6.710e+02, 2.710e+02, 1.930e+02, 5.000e+00, 4.900e+01, 1.280e+03,
       8.100e+01, 8.700e+02, 7.400e+01, 5.200e+01, 7.840e+02, 7.000e+00,
       3.370e+02, 2.160e+02, 1.490e+02, 7.130e+02, 8.400e+02, 3.900e+01,
       3.900e+02, 6.800e+01, 4.200e+01, 2.620e+02, 2.420e+02, 3.840e+02,
       5.400e+02, 1.400e+01, 1.010e+02, 1.910e+02, 1.590e+02, 4.700e+02,
       7.500e+02, 1.450e+02, 2.400e+02, 8.700e+01, 4.240e+02, 3.100e+02,
       9.700e+01, 4.950e+02, 2.800e+03, 1.800e+03, 2.434e+03, 2.430e+02,
       1.877e+03, 1.540e+02, 8.200e+01, 4.375e+03, 6.100e+01, 4.510e+02,
       1.740e+02, 4.300e+02, 6.000e+00, 7.150e+02, 3.000e+00, 1.400e+03,
       2.190e+02, 1.120e+02, 5.200e+02, 6.690e+02, 1.900e+03, 1.350e+02,
       5.360e+02, 9.820e+02, 3.910e+02, 3.670e+02, 4.000e+00, 4.600e+02,
       9.100e+01, 1.610e+02, 1.310e+02, 1.650e+02, 8.600e+01, 2.360e+02,
       7.700e+01, 4.670e+02, 1.670e+02, 1.470e+02, 1.960e+02, 3.490e+02,
       1.940e+02, 1.080e+02, 4.060e+02, 3.750e+02])

In [12]:
df_cp1['percentage_laid_off'].unique()

array([0.05  , 0.08  ,    nan, 0.15  , 0.7   , 0.03  , 0.11  , 0.1   ,
       1.    , 0.04  , 0.06  , 0.2   , 0.14  , 0.5   , 0.09  , 0.25  ,
       0.02  , 0.07  , 0.32  , 0.13  , 0.12  , 0.57  , 0.3   , 0.28  ,
       0.33  , 0.31  , 0.17  , 0.35  , 0.19  , 0.75  , 0.22  , 0.27  ,
       0.24  , 0.65  , 0.16  , 0.43  , 0.4   , 0.39  , 0.21  , 0.18  ,
       0.36  , 0.115 , 0.125 , 0.37  , 0.23  , 0.6   , 0.34  , 0.38  ,
       0.85  , 0.48  , 0.01  , 0.82  , 0.42  , 0.54  , 0.46  , 0.96  ,
       0.035 , 0.26  , 0.8   , 0.29  , 0.    , 0.55  , 0.45  , 0.67  ,
       0.9   , 0.95  , 0.054 , 0.0185, 0.72  , 0.49  , 0.44  , 0.53  ,
       0.41  , 0.98  ])

In [13]:
df_cp1['date'].unique()

array(['3/6/2023', '3/3/2023', '3/2/2023', '3/1/2023', '2/28/2023',
       '2/27/2023', '2/26/2023', '2/25/2023', '2/24/2023', '2/23/2023',
       '2/22/2023', '2/21/2023', '2/20/2023', '2/19/2023', '2/17/2023',
       '2/16/2023', '2/15/2023', '2/14/2023', '2/13/2023', '2/12/2023',
       '2/10/2023', '2/9/2023', '2/8/2023', '2/7/2023', '2/6/2023',
       '2/5/2023', '2/3/2023', '2/2/2023', '2/1/2023', '1/31/2023',
       '1/30/2023', '1/29/2023', '1/28/2023', '1/27/2023', '1/26/2023',
       '1/25/2023', '1/24/2023', '1/23/2023', '1/22/2023', '1/20/2023',
       '1/19/2023', '1/18/2023', '1/17/2023', '1/16/2023', '1/15/2023',
       '1/13/2023', '1/12/2023', '1/11/2023', '1/10/2023', '1/9/2023',
       '1/8/2023', '1/6/2023', '1/5/2023', '1/4/2023', '1/3/2023',
       '1/2/2023', '12/27/2022', '12/26/2022', '12/25/2022', '12/23/2022',
       '12/22/2022', '12/21/2022', '12/20/2022', '12/19/2022',
       '12/16/2022', '12/15/2022', '12/14/2022', '12/13/2022',
       '12/12/2022', '12/10/2022', '12/9/2022', '12/8/2022', '12/7/2022',
       '12/6/2022', '12/5/2022', '12/3/2022', '12/2/2022', '12/1/2022',
       '11/30/2022', '11/29/2022', '11/28/2022', '11/27/2022',
       '11/26/2022', '11/25/2022', '11/24/2022', '11/23/2022',
       '11/22/2022', '11/21/2022', '11/19/2022', '11/18/2022',
       '11/17/2022', '11/16/2022', '11/15/2022', '11/14/2022',
       '11/11/2022', '11/10/2022', '11/9/2022', '11/8/2022', '11/7/2022',
       '11/6/2022', '11/4/2022', '11/3/2022', '11/2/2022', '11/1/2022',
       '10/31/2022', '10/28/2022', '10/27/2022', '10/26/2022',
       '10/25/2022', '10/24/2022', '10/23/2022', '10/21/2022',
       '10/20/2022', '10/19/2022', '10/18/2022', '10/17/2022',
       '10/16/2022', '10/14/2022', '10/13/2022', '10/12/2022',
       '10/11/2022', '10/10/2022', '10/7/2022', '10/6/2022', '10/5/2022',
       '10/4/2022', '10/3/2022', '10/2/2022', '9/30/2022', '9/29/2022',
       '9/28/2022', '9/27/2022', '9/24/2022', '9/23/2022', '9/22/2022',
       '9/21/2022', '9/20/2022', '9/19/2022', '9/18/2022', '9/16/2022',
       '9/15/2022', '9/14/2022', '9/13/2022', '9/12/2022', '9/9/2022',
       '9/8/2022', '9/7/2022', '9/6/2022', '9/2/2022', '9/1/2022',
       '8/31/2022', '8/30/2022', '8/29/2022', '8/28/2022', '8/26/2022',
       '8/25/2022', '8/24/2022', '8/23/2022', '8/22/2022', '8/21/2022',
       '8/20/2022', '8/19/2022', '8/18/2022', '8/17/2022', '8/16/2022',
       '8/15/2022', '8/14/2022', '8/13/2022', '8/12/2022', '8/11/2022',
       '8/10/2022', '8/9/2022', '8/8/2022', '8/5/2022', '8/4/2022',
       '8/3/2022', '8/2/2022', '8/1/2022', '7/31/2022', '7/29/2022',
       '7/28/2022', '7/27/2022', '7/26/2022', '7/25/2022', '7/24/2022',
       '7/22/2022', '7/21/2022', '7/20/2022', '7/19/2022', '7/18/2022',
       '7/15/2022', '7/14/2022', '7/13/2022', '7/12/2022', '7/11/2022',
       '7/9/2022', '7/8/2022', '7/7/2022', '7/6/2022', '7/5/2022',
       '7/4/2022', '7/3/2022', '7/2/2022', '7/1/2022', '6/30/2022',
       '6/29/2022', '6/28/2022', '6/27/2022', '6/26/2022', '6/24/2022',
       '6/23/2022', '6/22/2022', '6/21/2022', '6/20/2022', '6/19/2022',
       '6/18/2022', '6/17/2022', '6/16/2022', '6/15/2022', '6/14/2022',
       '6/13/2022', '6/10/2022', '6/9/2022', '6/8/2022', '6/7/2022',
       '6/6/2022', '6/4/2022', '6/3/2022', '6/2/2022', '6/1/2022',
       '5/31/2022', '5/30/2022', '5/27/2022', '5/26/2022', '5/25/2022',
       '5/24/2022', '5/23/2022', '5/21/2022', '5/20/2022', '5/19/2022',
       '5/18/2022', '5/17/2022', '5/16/2022', '5/14/2022', '5/13/2022',
       '5/12/2022', '5/11/2022', '5/10/2022', '5/9/2022', '5/6/2022',
       '5/5/2022', '5/4/2022', '5/2/2022', '5/1/2022', '4/29/2022',
       '4/28/2022', '4/27/2022', '4/26/2022', '4/25/2022', '4/21/2022',
       '4/20/2022', '4/19/2022', '4/18/2022', '4/15/2022', '4/14/2022',
       '4/12/2022', '4/11/2022', '4/8/2022', '4/7/2022', '4/5/2022',
       '4/4/2022', '3/31/2022', '3/30/2022', '3/29/2022', '3/26/2022',
       '3/19/2022', '3/17/2022', '3/16/2022', '3/15/2022', '3/10/2022',
       '3/8/2022', '3/3/2022', '3/2/2022', '3/1/2022', '2/25/2022',
       '2/24/2022', '2/21/2022', '2/17/2022', '2/16/2022', '2/14/2022',
       '2/10/2022', '2/8/2022', '2/7/2022', '2/3/2022', '1/26/2022',
       '1/20/2022', '1/8/2022', '12/22/2021', '12/8/2021', '12/1/2021',
       '11/18/2021', '11/2/2021', '10/5/2021', '10/1/2021', '9/23/2021',
       '9/22/2021', '9/15/2021', '9/14/2021', '8/30/2021', '8/24/2021',
       '8/5/2021', '7/26/2021', '6/1/2021', '5/5/2021', '4/29/2021',
       '4/26/2021', '4/6/2021', '3/24/2021', '3/9/2021', '3/3/2021',
       '3/1/2021', '2/24/2021', '2/23/2021', '2/22/2021', '2/9/2021',
       '2/4/2021', '2/3/2021', '2/1/2021', '1/27/2021', '1/25/2021',
       '1/23/2021', '1/21/2021', '1/20/2021', '1/13/2021', '1/11/2021',
       '1/7/2021', '1/6/2021', '12/23/2020', '12/16/2020', '12/8/2020',
       '11/25/2020', '11/19/2020', '11/18/2020', '11/17/2020',
       '11/9/2020', '11/5/2020', '11/2/2020', '11/1/2020', '10/29/2020',
       '10/25/2020', '10/23/2020', '10/21/2020', '10/20/2020',
       '10/14/2020', '10/10/2020', '10/8/2020', '9/29/2020', '9/25/2020',
       '9/23/2020', '9/16/2020', '9/11/2020', '9/9/2020', '9/8/2020',
       '9/5/2020', '9/2/2020', '9/1/2020', '8/31/2020', '8/26/2020',
       '8/24/2020', '8/20/2020', '8/19/2020', '8/18/2020', '8/17/2020',
       '8/14/2020', '8/12/2020', '8/11/2020', '8/8/2020', '8/7/2020',
       '8/6/2020', '8/5/2020', '7/30/2020', '7/29/2020', '7/28/2020',
       '7/27/2020', '7/23/2020', '7/21/2020', '7/20/2020', '7/17/2020',
       '7/16/2020', '7/15/2020', '7/14/2020', '7/13/2020', '7/10/2020',
       '7/9/2020', '7/8/2020', '7/1/2020', '6/30/2020', '6/29/2020',
       '6/28/2020', '6/27/2020', '6/25/2020', '6/24/2020', '6/23/2020',
       '6/22/2020', '6/19/2020', '6/18/2020', '6/17/2020', '6/16/2020',
       '6/15/2020', '6/12/2020', '6/11/2020', '6/10/2020', '6/9/2020',
       '6/5/2020', '6/4/2020', '6/3/2020', '6/2/2020', '6/1/2020',
       '5/29/2020', '5/28/2020', '5/27/2020', '5/26/2020', '5/25/2020',
       '5/22/2020', '5/21/2020', '5/20/2020', '5/19/2020', '5/18/2020',
       '5/17/2020', '5/15/2020', '5/14/2020', '5/13/2020', '5/12/2020',
       '5/11/2020', '5/8/2020', '5/7/2020', '5/6/2020', '5/5/2020',
       '5/4/2020', '5/3/2020', '5/1/2020', '4/30/2020', '4/29/2020',
       '4/28/2020', '4/27/2020', '4/25/2020', '4/24/2020', '4/23/2020',
       '4/22/2020', '4/21/2020', '4/20/2020', '4/18/2020', '4/17/2020',
       '4/16/2020', '4/15/2020', '4/14/2020', '4/13/2020', '4/10/2020',
       '4/9/2020', '4/8/2020', '4/7/2020', '4/6/2020', '4/5/2020',
       '4/4/2020', '4/3/2020', '4/2/2020', '4/1/2020', '3/31/2020',
       '3/30/2020', '3/29/2020', '3/28/2020', '3/27/2020', '3/26/2020',
       '3/25/2020', '3/24/2020', '3/23/2020', '3/20/2020', '3/19/2020',
       '3/18/2020', '3/16/2020', '3/13/2020', '3/12/2020', '3/11/2020',
       nan], dtype=object)

In [14]:
df_cp1['stage'].unique()

array(['Post-IPO', 'Series B', 'Unknown', 'Acquired', 'Series F',
       'Series E', 'Series A', 'Subsidiary', 'Series C', 'Series G',
       'Series D', 'Seed', 'Series H', 'Private Equity', 'Series J', nan,
       'Series I'], dtype=object)

In [15]:
df_cp1['funds_raised_millions'].unique()

array([2.100e+02, 5.250e+02, 1.600e+01, 6.310e+02, 7.880e+02, 3.170e+02,
       5.900e+01, 1.520e+02, 6.400e+03, 4.580e+02, 1.200e+03, 1.480e+02,
       4.610e+02,       nan, 1.300e+01, 2.000e+01, 1.290e+04, 7.480e+02,
       2.100e+03, 4.820e+02, 5.500e+03, 4.950e+02, 1.020e+02, 8.390e+02,
       7.000e+01, 2.000e+00, 5.570e+02, 4.850e+02, 1.260e+02, 4.620e+02,
       2.830e+02, 3.000e+03, 4.890e+02, 4.010e+02, 6.630e+02, 1.300e+03,
       5.750e+02, 3.250e+02, 4.650e+02, 1.320e+02, 2.630e+02, 1.530e+02,
       4.420e+02, 4.000e+02, 7.600e+01, 6.070e+02, 6.100e+01, 2.790e+02,
       1.550e+02, 1.940e+02, 5.700e+01, 4.510e+02, 2.600e+01, 4.060e+02,
       2.140e+02, 1.210e+02, 4.670e+02, 7.900e+01, 1.000e+03, 1.000e+01,
       9.000e+00, 4.200e+03, 1.260e+04, 2.900e+02, 3.020e+02, 1.050e+02,
       5.360e+02, 6.200e+01, 3.560e+02, 1.100e+03, 5.800e+01, 7.200e+02,
       2.200e+01, 4.910e+02, 4.290e+02, 4.350e+02, 1.800e+02, 8.600e+01,
       6.300e+01, 1.850e+02, 1.100e+01, 4.000e+01, 3.110e+02, 6.140e+02,
       2.120e+02, 2.250e+02, 3.000e+01, 7.190e+02, 1.700e+02, 7.080e+02,
       7.490e+02, 1.800e+03, 1.540e+02, 1.380e+02, 9.400e+03, 1.400e+02,
       2.980e+02, 6.000e+00, 5.260e+02, 1.700e+03, 8.560e+02, 5.660e+02,
       4.130e+02, 2.180e+02, 1.920e+02, 3.500e+02, 8.000e+02, 1.500e+03,
       7.460e+02, 5.830e+02, 1.680e+02, 8.500e+01, 2.780e+02, 1.000e+02,
       1.500e+01, 2.760e+02, 8.300e+01, 2.450e+02, 2.990e+02, 5.600e+01,
       1.060e+02, 5.070e+02, 8.000e+01, 1.070e+02, 1.900e+01, 4.960e+02,
       2.300e+03, 1.830e+02, 4.200e+01, 1.500e+02, 1.600e+02, 4.760e+02,
       6.440e+02, 5.500e+01, 8.110e+02, 9.480e+02, 2.400e+02, 4.970e+02,
       2.400e+03, 1.610e+02, 4.150e+02, 2.150e+02, 2.800e+01, 1.900e+02,
       1.370e+02, 5.200e+01, 1.070e+04, 2.160e+02, 2.300e+02, 1.440e+02,
       3.440e+02, 1.600e+03, 2.350e+02, 1.200e+01, 6.290e+02, 1.400e+03,
       9.900e+03, 1.900e+03, 2.050e+02, 3.220e+02, 2.240e+02, 1.760e+02,
       4.250e+02, 4.300e+01, 1.010e+02, 3.900e+02, 4.500e+01, 2.100e+01,
       1.800e+01, 2.730e+02, 4.700e+01, 4.550e+02, 5.500e+02, 2.260e+02,
       5.000e+01, 1.710e+02, 6.460e+02, 5.100e+01, 6.570e+02, 8.340e+02,
       3.790e+02, 3.600e+01, 4.100e+01, 1.400e+01, 3.320e+02, 1.730e+02,
       2.300e+01, 2.700e+03, 3.200e+02, 2.950e+02, 9.700e+01, 6.900e+01,
       4.230e+02, 1.170e+02, 1.150e+02, 3.600e+03, 3.070e+02, 1.690e+02,
       1.000e+00, 6.400e+01, 3.410e+02, 1.560e+02, 9.100e+01, 2.220e+04,
       9.650e+02, 2.330e+02, 2.690e+02, 1.450e+02, 5.210e+02, 1.670e+02,
       1.250e+02, 1.720e+02, 2.530e+02, 5.710e+02, 1.790e+02, 4.160e+02,
       2.600e+02, 3.000e+02, 2.750e+02, 4.200e+02, 9.460e+02, 2.040e+02,
       2.000e+03, 5.400e+01, 8.540e+02, 8.700e+01, 3.360e+02, 9.200e+01,
       3.100e+01, 4.400e+01, 1.700e+01, 6.980e+02, 3.820e+02, 7.400e+01,
       5.480e+02, 1.040e+02, 2.540e+02, 5.000e+03, 1.140e+02, 3.920e+02,
       4.100e+02, 4.900e+02, 5.560e+02, 3.340e+02, 3.280e+02, 1.580e+02,
       3.400e+01, 3.500e+03, 5.650e+02, 2.440e+02, 3.490e+02, 9.400e+01,
       1.330e+02, 3.300e+01, 2.930e+02, 5.490e+02, 6.650e+02, 9.500e+01,
       7.260e+02, 1.780e+02, 1.110e+02, 1.200e+02, 2.230e+02, 3.830e+02,
       4.040e+02, 5.600e+02, 6.560e+02, 6.020e+02, 5.220e+02, 8.800e+01,
       9.990e+02, 3.260e+02, 4.720e+02, 1.160e+02, 8.630e+02, 9.800e+01,
       1.080e+02, 6.500e+01, 2.820e+02, 1.660e+02, 2.740e+02, 5.300e+02,
       4.500e+02, 2.900e+01, 6.200e+02, 3.700e+03, 8.000e+00, 9.600e+01,
       2.500e+01, 6.480e+02, 9.000e+01, 8.920e+02, 4.000e+00, 1.360e+02,
       7.400e+03, 7.040e+02, 4.840e+02, 5.100e+03, 6.860e+02, 1.750e+02,
       3.470e+02, 5.140e+02, 1.890e+02, 2.810e+02, 1.740e+02, 7.300e+01,
       5.370e+02, 8.200e+01, 2.200e+02, 2.310e+02, 4.590e+02, 9.320e+02,
       3.520e+02, 3.200e+01, 8.500e+02, 2.030e+02, 2.920e+02, 7.340e+02,
       5.670e+02, 5.150e+02, 6.130e+02, 3.150e+02, 1.390e+02, 6.790e+02,
       6.960e+02, 4.800e+02, 1.650e+02, 6.300e+02, 2.000e+02, 4.790e+02,
       6.470e+02, 2.650e+02, 1.030e+02, 3.230e+02, 4.810e+02, 4.000e+03,
       1.840e+02, 1.280e+02, 3.720e+02, 4.190e+02, 2.290e+02, 1.510e+02,
       3.210e+02, 2.500e+03, 1.340e+02, 1.910e+02, 5.440e+02, 1.180e+02,
       1.620e+02, 7.000e+02, 3.780e+02, 6.040e+02, 4.830e+02, 7.800e+01,
       3.890e+02, 1.570e+02, 3.000e+00, 2.640e+02, 9.000e+02, 8.090e+02,
       7.700e+02, 8.040e+02, 9.140e+02, 2.080e+02, 3.500e+01, 1.880e+02,
       8.890e+02, 4.520e+02, 4.360e+02, 4.090e+02, 5.010e+02, 4.530e+02,
       2.560e+02, 1.640e+02, 4.410e+02, 3.810e+02, 1.870e+02, 6.800e+01,
       7.910e+02, 4.050e+02, 6.240e+02, 5.970e+02, 5.930e+02, 3.550e+02,
       1.190e+02, 8.100e+01, 2.770e+02, 2.600e+04, 3.100e+02, 5.270e+02,
       4.750e+02, 7.200e+01, 2.570e+02, 7.310e+02, 8.380e+02, 2.800e+02,
       5.000e+00, 6.000e+01, 3.800e+02, 4.900e+03, 4.280e+02, 8.300e+03,
       4.450e+02, 4.680e+02, 0.000e+00, 3.770e+02, 4.770e+02, 5.680e+02,
       2.130e+02, 1.630e+02, 7.500e+02, 6.830e+02, 5.530e+02, 1.420e+02,
       8.490e+02, 1.270e+02, 3.650e+02, 3.400e+03, 1.770e+02, 5.960e+02,
       3.130e+02, 7.100e+01, 1.220e+02, 4.260e+02, 2.170e+02, 3.670e+02,
       5.850e+02, 6.450e+02, 5.340e+02, 3.600e+02, 2.550e+02, 2.370e+02,
       3.850e+02, 6.920e+02, 2.900e+03, 7.060e+02, 4.740e+02, 7.500e+01,
       4.560e+02, 2.710e+02, 6.700e+01, 1.219e+05, 1.970e+02, 8.400e+01,
       2.470e+04, 4.690e+02, 1.430e+02, 8.600e+03, 2.500e+02, 9.100e+02,
       2.210e+02, 1.230e+02, 2.870e+02, 9.740e+02, 9.050e+02, 3.610e+02,
       3.300e+02, 2.400e+01, 2.090e+02, 7.700e+01, 3.050e+02, 2.010e+02,
       2.380e+02, 3.010e+02, 5.330e+02, 3.380e+02, 5.040e+02, 2.720e+02,
       8.140e+02, 7.000e+00, 4.780e+02, 5.350e+02, 6.520e+02, 2.420e+02,
       3.900e+01, 5.420e+02, 5.600e+03, 3.420e+02, 2.660e+02, 6.810e+02,
       5.100e+02, 1.300e+02, 2.020e+02, 3.940e+02, 3.290e+02, 2.470e+02,
       2.800e+03, 9.920e+02, 4.800e+01, 1.590e+02, 7.660e+02, 5.700e+02,
       8.170e+02, 2.700e+01, 4.270e+02, 8.900e+01, 5.300e+01, 2.410e+02,
       1.090e+02, 6.400e+02, 8.810e+02, 3.510e+02, 5.700e+03, 5.690e+02,
       3.350e+02, 8.640e+02, 3.800e+01, 1.350e+02, 1.120e+02, 4.110e+02,
       7.430e+02, 6.900e+02, 5.460e+02, 1.240e+02, 5.000e+02, 2.610e+02,
       4.600e+02, 2.480e+02, 4.900e+01, 4.300e+02, 9.300e+01, 3.190e+02,
       3.760e+02, 9.260e+02, 1.490e+02, 7.830e+02, 6.030e+02, 2.590e+02,
       1.100e+02, 2.020e+04, 2.860e+02, 3.700e+01, 1.820e+02, 3.750e+02,
       4.600e+01, 1.950e+02, 6.190e+02, 9.170e+02, 5.020e+02, 7.550e+02,
       7.520e+02, 2.280e+02, 6.540e+02, 2.890e+02, 3.680e+02, 3.390e+02,
       2.145e+02, 1.860e+02, 2.142e+02, 7.630e+02, 5.840e+02, 1.310e+02,
       3.200e+03, 3.800e+00, 1.016e+02, 1.250e+01, 3.500e+00, 1.540e+00,
       1.950e+04, 1.579e+02, 4.050e+01, 1.340e+01, 2.280e+01, 9.520e+01,
       6.540e+01, 9.500e+00, 7.620e+01, 1.550e+01, 1.300e+00, 1.223e+02,
       3.502e+02, 2.300e+00, 9.755e-01, 1.864e+02, 1.800e+00, 4.240e+01,
       6.490e+02, 6.018e+01, 2.970e+01, 3.090e+02, 4.046e+02, 2.240e+01,
       2.512e+02, 1.972e+02, 3.076e+02, 2.560e+01, 5.780e+01, 1.008e+02,
       4.552e+02, 4.800e+03, 5.820e+02, 3.960e+01, 3.240e+02, 3.100e+03,
       7.320e+02, 3.400e+02, 2.070e+02, 1.460e+02, 3.800e+03, 2.220e+02,
       2.520e+02, 5.300e+03, 5.740e+02, 8.370e+02, 7.820e+02, 5.400e+03,
       1.810e+02, 7.710e+02, 3.860e+02, 6.600e+02, 2.250e+03, 7.650e+02,
       8.400e+02, 2.600e+03, 2.200e+03, 2.880e+02, 4.470e+02, 3.580e+02,
       9.550e+02, 6.890e+02, 1.375e+02, 3.140e+02, 9.020e+02, 4.380e+02,
       9.900e+01, 7.000e-01, 2.270e+02, 3.480e+02, 2.970e+02, 8.500e+00,
       2.190e+02, 5.410e+02, 6.230e+02, 4.030e+02, 9.810e+02, 1.791e+02,
       2.960e+02, 3.590e+02, 5.100e+00])

In [16]:
df_cp1['industry'], _filler  = lib.fillnull(df_cp1['industry'])
filler_values.update(_filler)

In [17]:
df_cp1['total_laid_off'], _filler  = lib.fillnull(df_cp1['total_laid_off'], 0)
filler_values.update(_filler)
df_cp1['total_laid_off'] = df_cp1['total_laid_off'].astype(int)

In [18]:
df_cp1['percentage_laid_off'], _filler  = lib.fillnull(df_cp1['percentage_laid_off'], 0)
filler_values.update(_filler)
df_cp1['percentage_laid_off'] = df_cp1['percentage_laid_off'].astype(float)

Converting column `date` to Timestamp

In [19]:
df_cp1['date']

0         3/6/2023
1         3/6/2023
2         3/6/2023
3         3/6/2023
4         3/3/2023
           ...
2356           NaN
2357      2/9/2023
2358     3/30/2020
2359     9/14/2021
2360    11/28/2022
Name: date, Length: 2361, dtype: object

In [20]:
df_cp1['date'] = pd.to_datetime(df_cp1['date'])

In [21]:
df_cp1['date'], _filler = lib.fillnull(df_cp1['date'])
filler_values.update(_filler)

In [22]:
filler_values

{'industry': 'Not Available',
 'total_laid_off': 0,
 'percentage_laid_off': 0,
 'date': Timestamp('2262-04-11 23:47:16.854775807')}

In [23]:
df_cp1['stage'].unique()

array(['Post-IPO', 'Series B', 'Unknown', 'Acquired', 'Series F',
       'Series E', 'Series A', 'Subsidiary', 'Series C', 'Series G',
       'Series D', 'Seed', 'Series H', 'Private Equity', 'Series J', nan,
       'Series I'], dtype=object)

In [24]:
df_cp1['stage'], _filler = lib.fillnull(df_cp1['stage'], default='Unknown')
filler_values.update(_filler)
filler_values

{'industry': 'Not Available',
 'total_laid_off': 0,
 'percentage_laid_off': 0,
 'date': Timestamp('2262-04-11 23:47:16.854775807'),
 'stage': 'Unknown'}

In [25]:
df_cp1['funds_raised_millions'], _filler = lib.fillnull(df_cp1['funds_raised_millions'], default=0)
filler_values.update(_filler)
filler_values

{'industry': 'Not Available',
 'total_laid_off': 0,
 'percentage_laid_off': 0,
 'date': Timestamp('2262-04-11 23:47:16.854775807'),
 'stage': 'Unknown',
 'funds_raised_millions': 0}

In [26]:
df_cp1['funds_raised_millions'] = df_cp1['funds_raised_millions'].astype(int)
df_cp1['funds_raised_millions']

0       210
1       525
2        16
3       631
4       788
       ...
2356      0
2357      6
2358     45
2359    339
2360    260
Name: funds_raised_millions, Length: 2361, dtype: int64

## Validating we've updated null values

In [27]:
lib.hasnull(df_cp1).sum()
df_cp1.isnull().sum()

company                  0
location                 0
industry                 0
total_laid_off           0
percentage_laid_off      0
date                     0
stage                    0
country                  0
funds_raised_millions    0
dtype: int64

## Creating a backup

In [28]:
df_cp2 = df_cp1.copy()

## Checking the rest of the columns

In [29]:
df_cp2.columns

Index(['company', 'location', 'industry', 'total_laid_off',
       'percentage_laid_off', 'date', 'stage', 'country',
       'funds_raised_millions'],
      dtype='object')

In [30]:
lib.get_close_matches(df_cp2['company'])

{'#Paid',
 '&Open',
 'Acast',
 'Airtable',
 'Airtame',
 'Airtime',
 'Apollo Insurance',
 'AppGate',
 'Appgate',
 'Article',
 'Articulate',
 'Avast',
 'Baton',
 'BitGo',
 'Bitso',
 'Bolt',
 'Bounce',
 'BounceX',
 'Breathe',
 'Breather',
 'Brighte',
 'Brightline',
 'ByteDance',
 'Bytedance',
 'Byton',
 'Canoo',
 'Carbon',
 'Care.com',
 'Cart.com',
 'Cazoo',
 'Cedar',
 'Century Therapeutics',
 'Checkmarx',
 'Checkr',
 'Cheddar',
 'Clear',
 'ClearCo',
 'Clearco',
 'Clue',
 'Cogito',
 'Copper',
 'Cue',
 'CureFit',
 'Curefit',
 'CyCognito',
 'Cyteir Therapeutics',
 'DISCO',
 'DSCO',
 'Datera',
 'Docly',
 'Domio',
 'Domo',
 'Dooly',
 'Dover',
 'Element',
 'Element AI',
 'Elementor',
 'Enjoy',
 'Envoy',
 'Fate Therapeutics',
 'Feather',
 'Freshbooks',
 'Freshworks',
 'GOAT Group',
 'Gather',
 'Gatherly',
 'Genius',
 'GoBolt',
 'GoTo Group',
 'GoodGood',
 'Goodfood',
 'Hopin',
 'Hopper',
 'Impossible Foods',
 'Impossible Foods copy',
 'Jumia',
 'Jumio',
 'Karbon',
 'Kazoo',
 'Koho',
 'Komodo Health',
 'Koo',
 'Lendi',
 'Lendis',
 'Loop',
 'LoopMe',
 'Loopio',
 'Lucira Health',
 'Matrixport',
 'Matterport',
 'Maven',
 'Mavenir',
 'Momentive',
 'Moove',
 'Moovel',
 'Motive',
 'Natera',
 'Nav',
 'Navi',
 'Newfront Insurance',
 'Next Insurance',
 'Nomad Health',
 'OfferUp',
 'Offerpad',
 'On Deck',
 'OnDeck',
 'OpenX',
 'Pear Therapeutics',
 'Pier',
 'Plaid',
 'Popin',
 'Primer',
 'Quora',
 'Root Insurance',
 'Rover',
 'SQream',
 'Sage Therapeutics',
 'SalesLoft',
 'Salesloft',
 'Sana',
 'Sanar',
 'Sauce Labs',
 'Scoop',
 'Scoro',
 'SendCloud',
 'Shift',
 'Sift',
 'Simple',
 'Slice Labs',
 'Snap',
 'Snappy',
 'SoundCloud',
 'Spaces',
 'Spaceship',
 'Spring',
 'Springbig',
 'Stream',
 'Sundae',
 'Sunday',
 'SundaySky',
 'Swyft',
 'Swyftx',
 'Tackle',
 'Takl',
 'TomTom',
 'Tomo',
 'TuSimple',
 'Vanta',
 'Vee',
 'Veem',
 'Veev',
 'Viamo',
 'Viant',
 'Vibrent Health',
 'Vimeo',
 'Virta Health',
 'Wave',
 'Wavely',
 'Willow',
 'Wonder',
 'Wordstream',
 'Workstream',
 'Yonder',
 'Zapp',
 'Zappos',
 'Zenius',
 'Zepto',
 'Zerto',
 'Zillow',
 'Ziroom',
 'Zola',
 'Zoom',
 'Zoomo',
 'Zoopla',
 'Zum',
 'Zume',
 'Zumper',
 'Zuora',
 'tZero'}

In [31]:
to_replace = {
    'Airtame': 'Airtime',
    'Appgate': 'AppGate',
    'Bytedance': 'ByteDance',
    'Clearco': 'ClearCo',
    'Curefit': 'CureFit',
    'Impossible Foods copy': 'Impossible Foods',
    'Salesloft': 'SalesLoft',
    'On Deck': 'OnDeck'
}

for key, value in to_replace.items():
    df_cp2['company'] = df_cp2['company'].str.replace(key, value)

In [32]:
lib.get_close_matches(df_cp2['company'], cutoff=.9)

{'Bounce',
 'BounceX',
 'Breathe',
 'Breather',
 'Lendi',
 'Lendis',
 'Moove',
 'Moovel',
 'Swyft',
 'Swyftx',
 'Wordstream',
 'Workstream'}

In [33]:
lib.has_duplicates(df_cp2['company'])
dict(sorted(lib.values_counter(df_cp2['company']).items()))

{'#Paid': 1,
 '&Open': 1,
 '100 Thieves': 2,
 '10X Genomics': 1,
 '1stdibs': 1,
 '2TM': 2,
 '2U': 1,
 '54gene': 1,
 '5B Solar': 1,
 '6sense': 1,
 '80 Acres Farms': 1,
 '8x8': 2,
 '98point6': 1,
 '99': 1,
 'AU10TIX': 1,
 'Abra': 1,
 'Absci': 1,
 'Acast': 1,
 'Accolade': 1,
 'Acko': 1,
 'Acorns': 1,
 'Actifio': 1,
 'ActiveCampaign': 1,
 'AdRoll': 1,
 'Ada': 2,
 'Ada Health': 1,
 'Ada Support': 1,
 'Adaptive Biotechnologies': 1,
 'Adara': 1,
 'Addepar': 1,
 'Addi': 1,
 'Adobe': 1,
 'Advata': 1,
 'Adwerx': 1,
 'Affirm': 2,
 'Afterverse': 1,
 'Agoda': 1,
 'Ahead': 1,
 'Air': 1,
 'AirMap': 1,
 'Airbnb': 2,
 'Airlift': 2,
 'Airtable': 1,
 'Airtasker': 1,
 'Airtime': 2,
 'Airy Rooms': 2,
 'Aiven': 1,
 'Ajaib': 1,
 'Akerna': 2,
 'Akili Labs': 1,
 'Akulaku': 1,
 'AlayaCare': 1,
 'Albert': 1,
 'Alegion': 1,
 'Alerzo': 2,
 'AliExpress Russia': 1,
 'Alice': 2,
 'Allbirds': 1,
 'AllyO': 1,
 'Almanac': 1,
 'Alto Pharmacy': 2,
 'Amazon': 3,
 'Amber Group': 1,
 'Ambev Tech': 1,
 'Amdocs': 1,
 'American Robotics': 1,
 'Amobee': 1,
 'Amount': 2,
 'Amperity': 1,
 'Amplero': 1,
 'Anagram': 1,
 'Andela': 1,
 'AngelList': 1,
 'Anodot': 1,
 'Antidote Health': 1,
 'Anyvision': 1,
 'Anywell': 1,
 'Apartment List': 1,
 'Apeel Sciences': 1,
 'Apollo': 1,
 'Apollo Insurance': 1,
 'App Annie': 1,
 'AppGate': 2,
 'AppLovin': 1,
 'ApplyBoard': 1,
 'Aqgromalin': 1,
 'Aqua Security': 2,
 'Arc': 1,
 'Arch Oncology': 2,
 'Arete': 1,
 'Argo AI': 4,
 'Argyle': 1,
 'Armis': 1,
 'Arrival': 3,
 'Arrive Logistics': 1,
 'Article': 1,
 'Articulate': 1,
 'Artnight': 1,
 'Asana': 1,
 'AskNicely': 1,
 'Aspire': 1,
 'Assure': 1,
 'Astra': 2,
 'Astronomer': 1,
 'Atlanta Tech Village': 1,
 'Atlas Obscura': 1,
 'Atlassian': 1,
 'AtoB': 1,
 'Atome': 1,
 'Atsu': 1,
 'Attentive': 1,
 'Augury': 1,
 'Aura': 1,
 'Aura Financial': 2,
 'Autobooks': 1,
 'Autodesk': 1,
 'Autograph': 1,
 'Automatic': 1,
 'Automation Anywhere': 1,
 'Automox': 2,
 'Avalara': 1,
 'AvantStay': 2,
 'Avantage Entertainment': 1,
 'Avast': 1,
 'Avo': 1,
 'Aware': 1,
 'Away': 1,
 'Awok': 1,
 'Aya': 1,
 'B8ta': 1,
 'BM Technologies': 1,
 'BUX': 1,
 'BVAccel': 1,
 'Babylon': 1,
 'Back Market': 1,
 'Bakkt': 1,
 "Bally's Interactive": 1,
 'Balto': 2,
 'Bamboo Health': 1,
 'Banxa': 1,
 'Baraja': 1,
 'Bark': 1,
 'Baton': 1,
 'Bcredi': 1,
 'Beam Benefits': 1,
 'Beamery': 1,
 'Beat': 1,
 'BeeTech': 1,
 'Bench': 1,
 'Benevity': 1,
 'Benitago Group': 1,
 'Berkeley Lights': 1,
 'Berlin Brands Group': 1,
 'Bestow': 1,
 'Better.com': 4,
 'BetterCloud': 1,
 'Betterfly': 2,
 'Betterment': 1,
 'Bevi': 1,
 'Beyond Meat': 2,
 'BeyondMinds': 1,
 'BharatAgri': 1,
 'Big Fish Games': 1,
 'BigBear.ai': 1,
 'BigCommerce': 1,
 'Bikayi': 1,
 'Bilibili': 1,
 'BioMarin': 1,
 'Bird': 2,
 'BitGo': 1,
 'BitMEX': 2,
 'BitOasis': 1,
 'BitSight': 1,
 'BitTitan': 1,
 'BitTorrent': 1,
 'Bitfarms': 1,
 'Bitfront': 1,
 'Bitpanda': 1,
 'Bitrise': 1,
 'Bitso': 2,
 'Bittrex': 1,
 'Bizongo': 1,
 'Bizpay': 1,
 'Bizzabo': 2,
 'Black Shark': 1,
 'BlackBuck': 1,
 'BlackLine': 1,
 'Blackbaud': 1,
 'Bleacher Report': 1,
 'Blend': 4,
 'BlockFi': 2,
 'Blockchain.com': 2,
 'BloomTech': 1,
 'Blue Apron': 1,
 'BlueStacks': 1,
 'Blueground': 1,
 'Blume Global': 1,
 'Bluprint': 1,
 'Bolt': 3,
 'Bond': 1,
 'Bonsai': 2,
 'Bonterra': 1,
 'BookClub': 1,
 'BookMyShow': 1,
 'Booking.com': 2,
 'Booksy': 1,
 'Booktopia': 2,
 'Boosted Commerce': 1,
 'Boozt': 1,
 'Borrowell': 1,
 'Bossa Nova': 2,
 'Bounce': 4,
 'BounceX': 1,
 'Brainbase': 1,
 'Brainly': 1,
 'Branch': 1,
 'Branch Metrics': 1,
 'Brave Care': 1,
 'Breathe': 1,
 'Breather': 1,
 'Brex': 2,
 'Bridge Connector': 1,
 'Bridgit': 1,
 'Bright Machines': 1,
 'Bright Money': 1,
 'Brighte': 2,
 'Brightline': 1,
 'Bringg': 1,
 'Britishvolt': 1,
 'Briza': 1,
 'Brodmann17': 1,
 'Bryter': 1,
 'Buenbit': 1,
 'Builder': 1,
 'Built In': 2,
 'Bullhorn': 1,
 'Bullish': 1,
 'Bungalow': 1,
 'BusBud': 1,
 'Buser': 1,
 'Bustle Digital Group': 3,
 'Butler Hospitality': 1,
 'Butterfly Network': 2,
 'Button': 1,
 'Buy.com / Rakuten': 1,
 'BuzzFeed': 1,
 'Buzzer': 1,
 'Bybit': 3,
 "Byju's": 2,
 'ByteDance': 4,
 'Byton': 1,
 'C2FO': 1,
 'C6 Bank': 2,
 'CNET': 1,
 'CS Disco': 1,
 'CTO.ai': 1,
 'Cabin': 1,
 'Cadre': 1,
 'Calibrate': 1,
 'Caliva': 1,
 'Callisto Media': 2,
 'Calm': 1,
 'Cameo': 2,
 'Camp K12': 1,
 'Candidate Labs': 1,
 'Candy Digital': 1,
 'Canoo': 1,
 'Capillary': 1,
 'Capital One': 1,
 'Capiter': 1,
 'Capitolis': 2,
 'Capsule': 1,
 'Captain Fresh': 1,
 'CaptivateIQ': 1,
 'CarDekho': 2,
 'CarGurus': 1,
 'Carbon': 1,
 'Carbon Health': 2,
 'Cardlytics': 1,
 'Care.com': 1,
 'CareRev': 1,
 'Careem': 1,
 'Career Karma': 2,
 'CareerArc': 1,
 'Caribou': 1,
 'Carousell': 1,
 'Cars24': 1,
 'Carsome': 1,
 'Cart.com': 1,
 'Carta': 2,
 'Carvana': 3,
 'Carwow': 1,
 'Casavo': 1,
 'Cashfree Payments': 1,
 'Casper': 3,
 'Castlight Health': 1,
 'Catalant': 1,
 'Catalyst': 1,
 'Catch.com.au': 1,
 'Cazoo': 3,
 'Cedar': 1,
 'Celsius': 1,
 'Century Therapeutics': 1,
 'Cerebral': 3,
 'Chainalysis': 1,
 'Change Invest': 1,
 'Change.org': 1,
 'Chargebee': 1,
 'Checkmarx': 2,
 'Checkout.com': 1,
 'Checkr': 1,
 'Cheddar': 1,
 'Cheetah': 1,
 'Chef': 1,
 'Chessable': 1,
 'Chili Piper': 1,
 'Chime': 1,
 'Chipax': 1,
 'Chipper Cash': 2,
 'Chope': 1,
 'ChowNow': 2,
 'Chrono24': 2,
 'CipherTrace': 1,
 'Circ': 1,
 'CircleCI': 1,
 'CircleUp': 1,
 'Circulo Health': 1,
 'Cisco': 1,
 'Citizen': 1,
 'Citrine Informatics': 1,
 'Citrix': 1,
 'CityMall': 1,
 'Claravine': 1,
 'Clari': 2,
 'Clarify Health': 1,
 'ClassPass': 1,
 'Classkick': 1,
 'Clear': 1,
 'Clear Capital': 2,
 'ClearCo': 4,
 'Clearbanc': 1,
 'Clearbit': 1,
 'Clever Real Estate': 2,
 'CleverTap': 1,
 'ClickUp': 1,
 'Clinc': 1,
 'CloudFactory': 1,
 'CloudKitchens': 1,
 'Cloudera': 1,
 'Cloudinary': 1,
 'Clubhouse': 1,
 'Clue': 1,
 'Clumio': 1,
 'Clutch': 2,
 'Clutter': 1,
 'Clyde': 1,
 'CoSchedule': 1,
 'CoachHub': 1,
 'Coda': 1,
 'Code42': 2,
 'CodeCombat': 1,
 'Codexis': 1,
 'Coding Dojo': 1,
 'Cogito': 1,
 'Cognyte': 1,
 'Cohesity': 1,
 'CoinDCX': 1,
 'CoinFLEX': 1,
 'CoinJar': 1,
 'CoinTracker': 1,
 'Coinbase': 3,
 'Coinsquare': 1,
 'Collective Health': 1,
 'Collibra': 1,
 'Color Health': 1,
 'Colossus': 1,
 'CommentSold': 1,
 'CommerceHub': 1,
 'CommonBond': 2,
 'Community': 1,
 'Compass': 4,
 'Compete': 1,
 'Confluent': 1,
 'Conga': 1,
 'Connected': 1,
 'ConsenSys': 2,
 'Consider.co': 1,
 'ContaAzul': 1,
 'ContraFect': 1,
 'Convene': 2,
 'Convoy': 4,
 'Copper': 1,
 'Core Scientific': 1,
 'Corvus Insurance': 1,
 'Cosuno': 1,
 'Coterie Insurance': 1,
 'Coursera': 1,
 'Crayon': 1,
 'CreateMe': 1,
 'Credit Sesame': 1,
 'Creditas': 1,
 'Crehana': 1,
 'Crejo.Fun': 1,
 'Criteo': 1,
 'CrowdRiff': 1,
 'CrowdStreet': 1,
 'Cruise': 1,
 'Crunchyroll': 1,
 'Crypto.com': 4,
 'Cue': 2,
 'Culture Amp': 1,
 'Culture Trip': 1,
 'Curative': 1,
 'CureFit': 2,
 'Curology': 1,
 'Currency': 1,
 'Curve': 1,
 'Cuyana': 1,
 'Cvent': 1,
 'CyCognito': 1,
 'CyberCube': 1,
 'Cybereason': 2,
 'Cypress.io': 1,
 'Cyren': 1,
 'Cyteir Therapeutics': 1,
 'D2L': 1,
 'D2iQ': 1,
 'DISCO': 1,
 'DJI': 2,
 'DSCO': 1,
 'DUX Education': 1,
 'Daily Harvest': 2,
 'DailyPay': 1,
 'Daloopa': 1,
 'Dance': 1,
 'Daniel Wellington': 1,
 'Dapper Labs': 2,
 'Daraz': 1,
 'Dark': 1,
 'DataRails': 1,
 'DataRobot': 4,
 'DataStax': 1,
 'Datera': 1,
 'Datto': 1,
 'DayTwo': 1,
 'Dazn': 1,
 'DeHaat': 2,
 'DealShare': 1,
 'Decent': 1,
 'Deep Instinct': 1,
 'Defined.ai': 1,
 'Definitive Healthcare': 1,
 'Degreed': 1,
 'Deliv': 1,
 'Deliveroo': 2,
 'Deliveroo Australia': 1,
 'Delivery Hero': 3,
 'Dell': 1,
 'Demandbase': 1,
 'Deputy': 1,
 'Descartes Labs': 1,
 'Desktop Metal': 3,
 'Devo': 1,
 'DialSource': 1,
 'Digimarc': 1,
 'Digital Currency Gruop': 1,
 'Digital Surge': 1,
 'DigitalOcean': 1,
 'Dispatch': 1,
 'Divergent 3D': 1,
 'Divvy': 1,
 'Divvy Homes': 3,
 'Dock': 1,
 'Docly': 1,
 'DocuSign': 2,
 'Doma': 3,
 'Domestika': 1,
 'Domino Data Lab': 1,
 'Domio': 2,
 'Domo': 1,
 'Dooly': 1,
 'DoorDash': 1,
 'Dotscience': 1,
 'Dover': 1,
 'DraftKings': 1,
 'DreamBox Learning': 1,
 'Drift': 1,
 'Drip': 1,
 'DriveWealth': 1,
 'Drop': 1,
 'Dropbox': 1,
 'Dude Solutions': 1,
 'Dukaan': 1,
 'Dunzo': 1,
 'Dutchie': 1,
 'Dynamic Signal': 1,
 'E Inc.': 1,
 'EMX Digital': 1,
 'EVgo': 1,
 'Earnin': 1,
 'Earth Rides': 1,
 'EasyPost': 2,
 'Eat Just': 1,
 'Eatsy': 1,
 'Eaze': 1,
 'Ebanx': 2,
 'Ecobee': 1,
 'Eden / Managed By Q': 1,
 'Edgio': 1,
 'Edifecs': 1,
 'Editas Medicine': 1,
 'Edmodo': 1,
 'Eight Sleep': 1,
 'Ejento': 1,
 'Elastic': 1,
 'Electric': 2,
 'Electronic Arts': 1,
 'Element': 1,
 'Element AI': 1,
 'Element Analytics': 1,
 'Elementor': 1,
 'Elemy': 2,
 'Elinvar': 1,
 'Elliptic': 1,
 'Embark': 1,
 'Embark Trucks': 1,
 'Embroker': 1,
 'Emitwise': 1,
 'Emotive': 1,
 'Engine eCommerce': 1,
 'Enjoei': 1,
 'Enjoy': 1,
 'Envato': 1,
 'Envoy': 1,
 'EquityZen': 1,
 'Equitybee': 2,
 'Ericsson': 1,
 'Ermetic': 1,
 'Eruditus': 1,
 'Esme Learning': 1,
 'Esper': 2,
 'Etermax': 1,
 'Ethos Life': 3,
 'Eucalyptus': 1,
 'Eventbrite': 2,
 'EverBridge': 1,
 'Everlane': 2,
 'Evernote': 1,
 'Exodus': 1,
 'Exotel': 1,
 'Expert360': 1,
 'Exterro': 1,
 'ExtraHop': 2,
 'F5': 1,
 'FabHotels': 1,
 'Fabric': 1,
 'Facily': 1,
 'Faire': 1,
 'Fandom': 2,
 'FarEye': 2,
 'Fareportal': 1,
 'Fast': 1,
 'Fate Therapeutics': 1,
 'Favo': 1,
 'Faze Medicines': 1,
 'Feather': 1,
 'Feedzai': 1,
 'Fifth Season': 1,
 'Filevine': 1,
 'Finastra': 1,
 'Finder': 1,
 'Finite State': 1,
 'Finleap Connect': 1,
 'Fipola': 1,
 'FireHydrant': 1,
 'Fireblocks': 1,
 'Firebolt': 1,
 'Firework': 1,
 'First AML': 1,
 'FiscalNote': 1,
 'Fishbrain': 1,
 'Fittr': 1,
 'Fiverr': 1,
 'Fivetran': 1,
 'Flash Coffee': 1,
 'Flatiron School': 1,
 'Flexport': 1,
 'Flipboard': 1,
 'Flipkart': 1,
 'FloQast': 1,
 'Flockjay': 1,
 'Flowhub': 1,
 'Flowr': 1,
 'Fluke': 1,
 'Flux Systems': 1,
 'Flyhomes': 2,
 'Flymya': 1,
 'Flynote': 1,
 'Flytedesk': 1,
 'Flywheel Sports': 1,
 'Flywire': 1,
 'Food52': 3,
 'Foodpanda': 3,
 'Foodsby': 1,
 'ForeScout': 1,
 'Foresight Insurance': 1,
 'Forma.ai': 1,
 'Forto': 1,
 'Forward': 2,
 'FourKites': 1,
 'Foxtrot': 1,
 'Fraazo': 1,
 'Freetrade': 1,
 'Frequency Therapeutics': 1,
 'FreshDirect': 1,
 'Freshbooks': 1,
 'Freshly': 2,
 'Freshworks': 1,
 'Front': 1,
 'FrontRow': 2,
 'Frontdesk': 1,
 'Frubana': 1,
 'FuboTV': 1,
 'FullStory': 2,
 'Fundbox': 2,
 'Funding Circle': 1,
 'Funding Societies': 1,
 'Fungible': 1,
 'Furlenco': 1,
 'FutureLearn': 1,
 'G/O Media Group': 1,
 'G2': 1,
 'GOAT Group': 1,
 'GSR': 1,
 'Gather': 1,
 'Gatherly': 1,
 'Gavelytics': 1,
 'Geekwire': 1,
 'Gem': 1,
 'Gemini': 3,
 'Genesis': 2,
 'Genius': 1,
 'Genome Medical': 1,
 'GetNinjas': 1,
 'GetYourGuide': 1,
 'Getaround': 2,
 'Getir': 3,
 'Getta': 1,
 'GitHub': 1,
 'GitLab': 1,
 'Gitpod': 1,
 'Give Legacy': 1,
 'Glassdoor': 1,
 'Glints': 1,
 'Glitch': 1,
 'GloriFi': 1,
 'Glossier': 3,
 'Glovo': 1,
 'GoBear': 1,
 'GoBolt': 1,
 'GoCanvas': 1,
 'GoCardless': 1,
 'GoDaddy': 2,
 'GoFundMe': 1,
 'GoHealth': 1,
 'GoMechanic': 1,
 'GoNuts': 1,
 'GoPro': 1,
 'GoSpotCheck': 1,
 'GoStudent': 2,
 'GoTo Group': 1,
 'Gojek': 1,
 'Gokada': 2,
 'Gong': 1,
 'GoodGood': 1,
 'GoodRx': 1,
 'Goodfood': 1,
 'Google': 1,
 'Gopuff': 4,
 'Gorillas': 2,
 'Grab': 1,
 'Grailed': 1,
 'Gramophone': 1,
 'Graphcore': 1,
 'GrayMeta': 1,
 'Green Labs': 1,
 'Greenhouse Software': 1,
 'Greenlight': 1,
 'Grin': 1,
 'Group Nine Media': 1,
 'Groupon': 3,
 'Grove Collaborative': 1,
 'Grover': 1,
 'Guardant Health': 1,
 'Guidewire': 1,
 'GumGum': 1,
 'Gusto': 1,
 'Gympass': 1,
 'HOOQ': 1,
 'HP': 1,
 'HackerEarth': 1,
 'Halcyon Health': 1,
 'Handshake': 1,
 'Happy Money': 1,
 'Harappa': 1,
 'Hash': 1,
 'HashiCorp': 1,
 'Haus': 1,
 'Havenly': 1,
 'Headspace': 1,
 'Health IQ': 1,
 'HealthMatch': 1,
 'Healthcare.com': 1,
 'HealthifyMe': 1,
 'Hedvig': 1,
 'HelloFresh': 1,
 'Help Scout': 1,
 'Help.com': 1,
 'Her Campus Media': 1,
 'Heroes': 1,
 'Heycar': 1,
 'Hibob': 2,
 'HighRadius': 1,
 'Highsnobiety': 1,
 'Highspot': 1,
 'Hipcamp': 1,
 'Hippo Insurance': 1,
 'Hirect': 1,
 'Hired': 1,
 'Hireology': 1,
 'Hodlnaut': 1,
 'Hologram': 1,
 'HomeLight': 1,
 'Homebot': 1,
 'Homebound': 1,
 'Homepoint': 1,
 'Homeward': 2,
 'Homie': 2,
 'Hootsuite': 3,
 'HopSkipDrive': 2,
 'Hopin': 3,
 'Hopper': 1,
 'Horizn Studios': 1,
 'Hotmart': 1,
 'Houzz': 2,
 'Hoxhunt': 1,
 'Huawei': 1,
 'HubHaus': 1,
 'HubSpot': 1,
 'Hubba': 1,
 'Hubilo': 2,
 'HuffPo': 1,
 'HumanForest': 1,
 'Humble': 1,
 'Humu': 1,
 'Hunty': 1,
 'Huobi': 2,
 'Hydrow': 2,
 'Hyperscience': 1,
 'IAM Robotics': 1,
 'IBM': 1,
 'ID.me': 1,
 'IRL': 1,
 'Ibotta': 1,
 'Icertis': 1,
 'Icon': 1,
 'Ideoclick': 1,
 'Iflix': 1,
 'Igenous': 1,
 'Ignite': 1,
 'Ignition': 1,
 'Ike': 1,
 'Illumina': 1,
 'Immersive Labs': 1,
 'Immutable': 2,
 'Impact.com': 1,
 'Impala': 1,
 'Imperfect Foods': 2,
 'Impossible Foods': 2,
 'Improbable': 1,
 'InDebted': 1,
 'InVision': 3,
 'Included Health': 1,
 'Incredible Health': 1,
 'Indigo': 2,
 'Industrious': 1,
 'Infarm': 2,
 'Influitive': 1,
 'InfluxData': 1,
 'InfoSum': 1,
 'Infogrid': 1,
 'Informatica': 1,
 'Inmobi': 1,
 'Innovaccer': 2,
 'Innovid': 1,
 'Inscripta': 1,
 'Inspectify': 1,
 'Inspirato': 2,
 'Instacart': 2,
 'Instamojo': 1,
 'Instructure': 1,
 'Intapp': 1,
 'Integral Ad Science': 2,
 'Integrate.ai': 1,
 'Intel': 2,
 'Intercom': 3,
 'Intersect': 1,
 'Intrinsic': 1,
 'Introhive': 1,
 'Intuit': 1,
 'Invitae': 1,
 'Involves': 1,
 'Iris Nova': 1,
 'Iron Ox': 1,
 'IronNet': 2,
 'JD.ID': 1,
 'JOKR': 1,
 'Jam City': 1,
 'Jama': 1,
 'Jellyfish': 1,
 'Jellysmack': 2,
 'JetClosing': 2,
 'Jetty': 1,
 'Jimdo': 1,
 'Jiobit': 1,
 'Jobcase': 1,
 'Jounce Therapeutics': 1,
 'Jumia': 1,
 'Jumio': 1,
 'Jump': 1,
 'Jumpcloud': 1,
 'Juni': 1,
 'Juniper': 1,
 'Juniper Square': 1,
 'Just Eat Takeaway': 1,
 'Juul': 2,
 'Kabam': 1,
 'Kaltura': 2,
 'Kandela': 1,
 'Kandji': 1,
 'Kaodim': 1,
 'Kapten / Free Now': 1,
 'Karat': 1,
 'Karbon': 1,
 'Katerra': 3,
 'Kavak': 2,
 'Kayak / OpenTable': 1,
 'Kazoo': 1,
 'KeepTruckin': 1,
 'Keepe': 1,
 'Kenoby': 1,
 'Khoros': 1,
 'Kiavi': 1,
 'Kickstarter': 1,
 'Kinde': 1,
 'Kite': 1,
 'Kitopi': 2,
 'Kitty Hawk': 2,
 'KiwiCo': 1,
 'Klarna': 2,
 'Klook': 1,
 'Knock': 1,
 'Knotel': 2,
 'Kodiak Robotics': 1,
 'Kogan': 1,
 'Koho': 2,
 'KoinWorks': 1,
 'Koinly': 1,
 'Komodo Health': 2,
 'Konfio': 1,
 'Kongregate': 1,
 'Kontist': 1,
 'Koo': 1,
 'Kraken': 1,
 'Kry': 2,
 'Kuda': 1,
 'Kueski': 1,
 'Kune': 1,
 'Kyruus': 1,
 'LEAD': 2,
 'Labelbox': 1,
 'Labster': 1,
 'Lacework': 1,
 'Ladder Life': 1,
 'Lam Research': 1,
 'Lambda School': 2,
 'Landing': 2,
 'Lantern': 1,
 'Lastline': 1,
 'Latch': 4,
 'Lattice': 3,
 'Lawgeex': 1,
 'Laybuy': 1,
 'Lazerpay': 1,
 'Le Tote': 1,
 'LeafLink': 1,
 'Leafly': 2,
 'League': 1,
 'LearnUpon': 1,
 'Ledn': 1,
 'Legible': 1,
 'Lemon': 1,
 'Lemonade': 1,
 'Lendi': 1,
 'Lending Club': 2,
 'LendingTree': 1,
 'Lendingkart': 1,
 'Lendis': 2,
 'Lenovo': 1,
 'LetsGetChecked': 1,
 'Lev': 1,
 'Levelset': 1,
 'Lever': 1,
 'Lido': 1,
 'Lido Learning': 1,
 'Life360': 1,
 'Liftoff': 1,
 'Lighter Capital': 2,
 'Lighthouse Labs': 1,
 'Lightico': 2,
 'Lightricks': 1,
 'Lightspeed Commerce': 1,
 'Lime': 1,
 'Limeade': 1,
 'Limelight': 1,
 'LinkedIn': 2,
 'Linkfire': 1,
 'Linktree': 1,
 'Liongard': 1,
 'Lithic': 1,
 'Liv Up': 1,
 'LivePerson': 2,
 'LiveRamp': 1,
 'LiveTiles': 1,
 'LiveVox': 1,
 'Livspace': 1,
 'Locomation': 1,
 'Loft': 6,
 'Loftium': 1,
 'Loftsmart': 1,
 'Loggi': 2,
 'Loja Integrada': 1,
 'Lokalise': 1,
 'Lola': 1,
 'Loom': 2,
 'Loop': 1,
 'LoopMe': 1,
 'Loopio': 1,
 'Lora DiCarlo': 1,
 'Lucid Diagnostics': 1,
 'Lucira Health': 1,
 'LumenAd': 1,
 'Lumina Networks': 1,
 'Lummo': 1,
 'Lunchbox': 1,
 'Luno': 1,
 'Lusha': 1,
 'Luxury Presence': 1,
 'Lyft': 3,
 'Lyric': 1,
 'Lyst': 1,
 'Lytics': 1,
 'M1': 1,
 'MFine': 1,
 'MX': 1,
 'Made.com': 1,
 'Madefire': 1,
 'MadeiraMadeira': 1,
 'Magic Eden': 1,
 'Magic Leap': 1,
 'Magicbricks': 1,
 'Magnite': 1,
 'Mainstreet': 1,
 'Make School': 1,
 'MakeMyTrip': 2,
 'MakerBot': 1,
 'Malwarebytes': 1,
 'Mapbox': 2,
 'Mapify': 1,
 'MariaDB': 1,
 'Mark43': 1,
 'Marketforce': 1,
 'Masse': 1,
 'MasterClass': 2,
 'Match Group': 1,
 'Matrixport': 1,
 'Matterport': 1,
 'Maven': 1,
 'Mavenir': 1,
 'MaxMilhas': 1,
 'McMakler': 2,
 'Me Poupe': 1,
 'Medallia': 1,
 'MediBuddy': 1,
 'MediaMath': 1,
 'Medium': 2,
 'Medly': 3,
 'Meero': 1,
 'Meesho': 3,
 'Megaport': 1,
 ...}

In [34]:
sorted(df_cp2['location'].unique())

['Accra',
 'Ahmedabad',
 'Albany',
 'Amsterdam',
 'Ann Arbor',
 'Athens',
 'Atlanta',
 'Auckland',
 'Austin',
 'Baltimore',
 'Bangkok',
 'Barcelona',
 'Baton Rouge',
 'Beau Vallon',
 'Beijing',
 'Belo Horizonte',
 'Bend',
 'Bengaluru',
 'Berlin',
 'Birmingham',
 'Bismarck',
 'Blumenau',
 'Bogota',
 'Boise',
 'Boston',
 'Boulder',
 'Brasilia',
 'Brisbane',
 'Bristol',
 'Brussels',
 'Bucharest',
 'Budapest',
 'Buenos Aires',
 'Burlington',
 'Cairo',
 'Calgary',
 'Cape Town',
 'Charleston',
 'Charlotte',
 'Chennai',
 'Chicago',
 'Cincinnati',
 'Coimbra',
 'Columbus',
 'Copenhagen',
 'Cork',
 'Curitiba',
 'Dakar',
 'Dallas',
 'Davenport',
 'Denver',
 'Detroit',
 'Dover',
 'Dubai',
 'Dublin',
 'Durham',
 'Dusseldorf',
 'Düsseldorf',
 'Edinburgh',
 'Eindhoven',
 'Fayetteville',
 'Ferdericton',
 'Florianópolis',
 'Frankfurt',
 'Gothenburg',
 'Grand Rapids',
 'Guadalajara',
 'Gurugram',
 'Hamburg',
 'Hanoi',
 'Helsinki',
 'Ho Chi Minh City',
 'Hong Kong',
 'Houston',
 'Huntsville',
 'Hyderabad',
 'Ibadan',
 'Indianapolis',
 'Indore',
 'Istanbul',
 'Jakarta',
 'Jersey City',
 'Jerusalem',
 'Joinville',
 'Kansas City',
 'Karachi',
 'Karlsruhe',
 'Kiel',
 'Krakow',
 'Kuala Lumpur',
 'Lagos',
 'Lahore',
 'Las Vegas',
 'Lehi',
 'Lexington',
 'Lima',
 'Lisbon',
 'Logan',
 'London',
 'Los Angeles',
 'Louisville',
 'Luxembourg',
 'Madison',
 'Malmo',
 'Malmö',
 'Manama',
 'Manchester',
 'Melbourne',
 'Mexico City',
 'Miami',
 'Milan',
 'Milwaukee',
 'Minneapolis',
 'Missoula',
 'Montevideo',
 'Montreal',
 'Moscow',
 'Mumbai',
 'Munich',
 'Nairobi',
 'Nashua',
 'Nashville',
 'Nebraska City',
 'New Delhi',
 'New Haven',
 'New Orleans',
 'New York City',
 'Noida',
 'Non-U.S.',
 'Norwalk',
 'Orlando',
 'Oslo',
 'Ottawa',
 'Oxford',
 'Paris',
 'Patna',
 'Philadelphia',
 'Phoenix',
 'Pittsburgh',
 'Portland',
 'Porto Alegre',
 'Prague',
 'Providence',
 'Pune',
 'Quebec',
 'Raleigh',
 'Reno',
 'Richmond',
 'SF Bay Area',
 'Sacramento',
 'Salt Lake City',
 'San Antonio',
 'San Diego',
 'San Luis Obispo',
 'Santa Barbara',
 'Santa Fe',
 'Santiago',
 'Sao Paulo',
 'Saskatoon',
 'Seattle',
 'Selangor',
 'Seoul',
 'Shanghai',
 'Shenzen',
 'Singapore',
 'Sofia',
 'Spokane',
 'St. Louis',
 'Stamford',
 'Stockholm',
 'Sydney',
 'Tallinn',
 'Tampa Bay',
 'Tel Aviv',
 'The Hague',
 'Tokyo',
 'Toronto',
 'Toulouse',
 'Trondheim',
 'Vancouver',
 'Victoria',
 'Vienna',
 'Vilnius',
 'Walldorf',
 'Washington D.C.',
 'Waterloo',
 'Wilmington',
 'Winnipeg',
 'Yangon',
 'Zug',
 'Zurich']

In [35]:
similar_words = lib.get_close_matches(df_cp2['location'])

In [36]:
similar_words

{'Dusseldorf', 'Düsseldorf', 'Malmo', 'Malmö'}

In [37]:
df_cp2['location'] = df_cp2['location'].str.replace('Dusseldorf', 'Düsseldorf')
df_cp2['location'] = df_cp2['location'].str.replace('Malmo', 'Malmö')

In [38]:
lib.get_close_matches(df_cp2['location'])

set()

In [39]:
df_cp2['industry'].unique()

array(['Other', 'Media', 'Retail', 'Education', 'Real Estate',
       'Transportation', 'Marketing', 'Not Available', 'Healthcare',
       'Security', 'Food', 'Fitness', 'Consumer', 'Logistics', 'HR',
       'Support', 'Travel', 'Crypto', 'Finance', 'Data', 'Sales',
       'Infrastructure', 'Hardware', 'Product', 'Construction', 'Legal',
       'Energy', 'Manufacturing', 'Recruiting', 'Aerospace',
       'Crypto Currency', 'Fin-Tech', 'CryptoCurrency'], dtype=object)

In [40]:
lib.get_close_matches(df_cp2['industry'])

{'Crypto Currency', 'CryptoCurrency'}

In [41]:
df_cp2['industry'] = df_cp2['industry'].str.replace('CryptoCurrency', 'Crypto Currency')

In [42]:
lib.get_close_matches(df_cp2['industry'])

set()

In [43]:
df_cp2['total_laid_off']

0        500
1        475
2        400
3        120
4        340
        ...
2356     500
2357    1600
2358      70
2359       0
2360     300
Name: total_laid_off, Length: 2361, dtype: int64

In [44]:
df_cp2['percentage_laid_off']

0       0.05
1       0.08
2       0.00
3       0.00
4       0.15
        ...
2356    0.14
2357    0.20
2358    0.30
2359    0.00
2360    0.20
Name: percentage_laid_off, Length: 2361, dtype: float64

In [45]:
lib.get_close_matches(df_cp2['stage'])

set()

In [46]:
lib.get_close_matches(df_cp2['country'])

set()

In [47]:
df_cp2

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500,0.05,2023-03-06 00:00:00.000000000,Post-IPO,Australia,210
1,SiriusXM,New York City,Media,475,0.08,2023-03-06 00:00:00.000000000,Post-IPO,United States,525
2,Alerzo,Ibadan,Retail,400,0.00,2023-03-06 00:00:00.000000000,Series B,Nigeria,16
3,UpGrad,Mumbai,Education,120,0.00,2023-03-06 00:00:00.000000000,Unknown,India,631
4,Loft,Sao Paulo,Real Estate,340,0.15,2023-03-03 00:00:00.000000000,Unknown,Brazil,788
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500,0.14,2262-04-11 23:47:16.854775807,Post-IPO,United States,0
2357,Yahoo,SF Bay Area,Consumer,1600,0.20,2023-02-09 00:00:00.000000000,Acquired,United States,6
2358,Hibob,Tel Aviv,HR,70,0.30,2020-03-30 00:00:00.000000000,Series A,Israel,45
2359,Casper,New York City,Retail,0,0.00,2021-09-14 00:00:00.000000000,Post-IPO,United States,339
2360,Wildlife Studios,Sao Paulo,Consumer,300,0.20,2022-11-28 00:00:00.000000000,Unknown,Brazil,260

# Final Cleaned Dataset

In [48]:
df_clean_data = df_cp2.copy()

## Export to CSV

In [58]:
lib.export_data(filename, df_clean_data)

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/layoffs/layoffs_CLEAN.csv')