# Cleaning Messy Chicago Traffic Crashes Dataset
Dataset from https://catalog.data.gov/dataset/budget

In [1]:
import pandas as pd
import importlib

import lib

importlib.reload(lib)

log = lib.logger.getLogger(__name__)

# Read dataset

In [2]:
filename = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/san_francisco_budget/san_francisco_budget.csv'
df = lib.tools.read_data(filename, sep=',', encoding='utf-8')

Encoding: utf-8
/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/lib/tools.py:52: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = fn(p, encoding=encoding, *args, **kwargs)
Stripping whitespaces from san_francisco_budget.csv

In [3]:
df

,Fiscal Year,Revenue or Spending,Related Govt Unit,Organization Group Code,Organization Group,Department Code,Department,Program Code,Program,Character Code,...,Sub-object,Fund Type Code,Fund Type,Fund Code,Fund,Fund Category Code,Fund Category,Budget,data_as_of,data_loaded_at
0,2015,Spending,Spending,2,"Public Works, Transportation & Commerce",MTA,Municipal Transportation Agency,BEG,Agency Wide Expenses,081,...,TIS-SFGTV Services (AAO),5M,MTA Municipal Railway Funds,5MAAA,Muni Operating Fund,5.0,Work Orders/Overhead,60447,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
1,2015,Spending,Spending,2,"Public Works, Transportation & Commerce",MTA,Municipal Transportation Agency,BE3,"Security, Safety, Training & Enforcement",013,...,Health Service-City Match,5M,MTA Municipal Railway Funds,5MAAA,Muni Operating Fund,5.0,Work Orders/Overhead,31292,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
2,2016,Spending,Spending,5,Culture & Recreation,REC,Recreation and Park Commission,EAA,Golden Gate Park,013,...,Social Security (OASDI & HI),7E,Expendable Trust Funds,7EGIF,Gift Fund,4.0,Grants,3388,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
3,2016,Spending,Spending,5,Culture & Recreation,REC,Recreation and Park Commission,EAA,Golden Gate Park,013,...,Social Security - Medicare (HI Only),1G,General Fund,1GAGF,General Fund,5.0,Work Orders/Overhead,1323,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
4,2016,Spending,Spending,5,Culture & Recreation,REC,Recreation and Park Commission,EAA,Golden Gate Park,040,...,Materials & Supplies-Budget,7E,Expendable Trust Funds,7EBEQ,Bequests Fund,4.0,Grants,89127,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378723,2012,Spending,Spending,6,General Administration & Finance,MYR,Mayor,FAJ,Neighborhood Services,040,...,Other Office Supplies,1G,General Fund,1GAGF,General Fund,1.0,Operating,4000,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
378724,2012,Spending,Spending,6,General Administration & Finance,MYR,Mayor,FEY,Public Policy & Finance,013,...,Health Service-City Match,1G,General Fund,1GAGF,General Fund,1.0,Operating,56225,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
378725,2012,Spending,Spending,6,General Administration & Finance,CON,Controller,FDC,Payroll And Personnel Services,040,...,Forms,1G,General Fund,1GAGF,General Fund,1.0,Operating,50000,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
378726,2012,Spending,Spending,6,General Administration & Finance,CON,Controller,FDC,Payroll And Personnel Services,021,...,Other Professional Services,1G,General Fund,1GAGF,General Fund,2.0,Annual Projects,871993,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM
378727,2012,Spending,Spending,6,General Administration & Finance,CON,Controller,FDC,Payroll And Personnel Services,001,...,Overtime - Misc,1G,General Fund,1GAGF,General Fund,1.0,Operating,15000,2025/08/31 10:07:35 PM,2025/09/01 02:03:23 AM

## Getting the general info to see what we're working with

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378728 entries, 0 to 378727
Data columns (total 24 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Fiscal Year              378728 non-null  int64
 1   Revenue or Spending      378728 non-null  object
 2   Related Govt Unit        378728 non-null  object
 3   Organization Group Code  378728 non-null  int64
 4   Organization Group       378728 non-null  object
 5   Department Code          378728 non-null  object
 6   Department               378728 non-null  object
 7   Program Code             378728 non-null  object
 8   Program                  378728 non-null  object
 9   Character Code           378728 non-null  object
 10  Character                378728 non-null  object
 11  Object Code              378728 non-null  object
 12  Object                   378728 non-null  object
 13  Sub-object Code          247656 non-null  object
 14  Sub-object               378728 non-null  object
 15  Fund Type Code           378728 non-null  object
 16  Fund Type                378728 non-null  object
 17  Fund Code                378728 non-null  object
 18  Fund                     378727 non-null  object
 19  Fund Category Code       378706 non-null  float64
 20  Fund Category            378706 non-null  object
 21  Budget                   378728 non-null  int64
 22  data_as_of               378728 non-null  object
 23  data_loaded_at           378728 non-null  object
dtypes: float64(1), int64(3), object(20)
memory usage: 69.3+ MB

### Checking for null indices and rows

In [5]:
null_indices, null_rows, null_columns = lib.tools.null_info(df)

4/24 columns contain null values
131117 total null values
-------------------------------------------------------------------------------
Column "Fiscal Year" has no null values
Column "Revenue or Spending" has no null values
Column "Related Govt Unit" has no null values
Column "Organization Group Code" has no null values
Column "Organization Group" has no null values
Column "Department Code" has no null values
Column "Department" has no null values
Column "Program Code" has no null values
Column "Program" has no null values
Column "Character Code" has no null values
Column "Character" has no null values
Column "Object Code" has no null values
Column "Object" has no null values
Column "Sub-object" has no null values
Column "Fund Type Code" has no null values
Column "Fund Type" has no null values
Column "Fund Code" has no null values
Column "Budget" has no null values
Column "data_as_of" has no null values
Column "data_loaded_at" has no null values
Column "Sub-object Code" has 131072 null values
Column "Fund" has 1 null values
Column "Fund Category Code" has 22 null values
Column "Fund Category" has 22 null values

Risk Rate ---------------------------------------------------------------------
Fiscal Year                0.000000
Revenue or Spending        0.000000
Related Govt Unit          0.000000
Organization Group Code    0.000000
Organization Group         0.000000
Department Code            0.000000
Department                 0.000000
Program Code               0.000000
Program                    0.000000
Character Code             0.000000
Character                  0.000000
Object Code                0.000000
Object                     0.000000
Sub-object Code            0.346085
Sub-object                 0.000000
Fund Type Code             0.000000
Fund Type                  0.000000
Fund Code                  0.000000
Fund                       0.000003
Fund Category Code         0.000058
Fund Category              0.000058
Budget                     0.000000
data_as_of                 0.000000
data_loaded_at             0.000000
dtype: float64

## No rows or columns that are ALL null. Moving onto cleaning columns.

## Creating a backup

In [6]:
df_cp1 = df.copy()

# Processing NaN Values

In [7]:
df_cp1.columns

Index(['Fiscal Year', 'Revenue or Spending', 'Related Govt Unit',
       'Organization Group Code', 'Organization Group', 'Department Code',
       'Department', 'Program Code', 'Program', 'Character Code', 'Character',
       'Object Code', 'Object', 'Sub-object Code', 'Sub-object',
       'Fund Type Code', 'Fund Type', 'Fund Code', 'Fund',
       'Fund Category Code', 'Fund Category', 'Budget', 'data_as_of',
       'data_loaded_at'],
      dtype='object')

## Checking for NaN and Non-NaN columns

In [8]:
# Create a null and non_null columns list
non_null_columns = lib.tools.notnull(df_cp1).columns
null_columns = lib.tools.hasnull(df_cp1).columns

log.info(non_null_columns)
log.info(null_columns)

Index(['Fiscal Year', 'Revenue or Spending', 'Related Govt Unit',
       'Organization Group Code', 'Organization Group', 'Department Code',
       'Department', 'Program Code', 'Program', 'Character Code', 'Character',
       'Object Code', 'Object', 'Sub-object', 'Fund Type Code', 'Fund Type',
       'Fund Code', 'Budget', 'data_as_of', 'data_loaded_at'],
      dtype='object')
Index(['Sub-object Code', 'Fund', 'Fund Category Code', 'Fund Category'], dtype='object')

## Checking for columns whose values are 75% or more NaN

In [9]:
# Get columns that mostly have NaN values. Will need to look at these closer.
high_risk = lib.tools.data_risks_rate(df_cp1, err_rate=.75)

Taking a look at the high risk columns

In [10]:
high_risk

Series([], dtype: float64)

## No High Risk columns. Moving onto check column 13 for mixed values

In [11]:
mixed_column = df_cp1.columns[13]

In [12]:
df_cp1.loc[:, mixed_column] = df_cp1.loc[:, mixed_column].astype(str)

In [13]:
df_cp1.loc[:, df_cp1.columns[13]]

0         081CW
1         01501
2         01401
3         01402
4         04000
          ...
378723    04951
378724    01501
378725    04931
378726    02799
378727    01101
Name: Sub-object Code, Length: 378728, dtype: object

## Moving onto filling null values.

In [14]:
null_columns

Index(['Sub-object Code', 'Fund', 'Fund Category Code', 'Fund Category'], dtype='object')

In [15]:
df_cp1['Fund']

0         Muni Operating Fund
1         Muni Operating Fund
2                   Gift Fund
3                General Fund
4               Bequests Fund
                 ...
378723           General Fund
378724           General Fund
378725           General Fund
378726           General Fund
378727           General Fund
Name: Fund, Length: 378728, dtype: object

### Checking Null values of column 'Fund'
Has only one null value

In [16]:
lib.tools.hasnull(df_cp1['Fund'])

52090    NaN
Name: Fund, dtype: object

Check of values in column 'Fund'

In [17]:
funds_counter = lib.tools.values_counter(df_cp1['Fund']).keys()

In [18]:
set(funds_counter)

{'2001 SFCCD Imprvt Bond-2002A',
 '2001 SFCCD Imprvt Bond-2004',
 '2001 SFCCD Imprvt Bond-C-2006',
 '2005 SFCCD G O  Bonds-A-2006',
 '2005 SFCCD Imprvt Bond-B-2007',
 '2005 SFCCD Imprvt Bond-C-2010',
 '2005 SFCCD Imprvt Bond-D-2010',
 '2015 AFFORD HOUS GOB 2nd 2018D',
 '2015 AFFORD HOUS GOB 3RD 2019C',
 'AgencyWide Oper Overhead',
 'Airport Capital Projects Fund',
 'Airport Operating Fund',
 'Airport Special Revenue Fund',
 'Bay Area Air Quality Mgmt Div',
 'Bay Area Rapid Transit',
 'Bayshore Hester Spcl Assmnt Fd',
 'Bequests Fund',
 'Bicycle Operating Fund',
 'Building Inspection Fund',
 'Bus Improv & Commty Bnfit Dist',
 'COP  War Memorial Vtrns S16A',
 'CP COP Animal Care&Contrl Proj',
 'CP City Fac Impvt-Other',
 'CP City Fac Impvt-Unallocated',
 'CP Cmed Building',
 'CP Fire Protctn Sys Impvt-Oth',
 'CP R&P Capital Impvt-Oth',
 'CP R&P Capital Impvt-Sta',
 'CP R&P Capital Impvt-Una',
 'CP R&P Capital Impvts-Fed',
 'CP SF Capital Planning',
 'CPEQS EARTHQUAKE SFTY IMP-UNA',
 'CPF Moscone Ctr Expansion',
 'CPMCF COP MOS CTR PROJ S2013A',
 'CPMCF COP MOS EXP PROJ 2013',
 'CPRPF 08 CLN&SF NEIG PK S2008B',
 'CPRPF 08 CLN&SF NEIG PK S2010B',
 'CPRPF 08 CLN&SF NEIG PK S2010D',
 'CPRPF 08 CLN&SF NEIG PK S2012B',
 'CPRPF 08 CLN&SF NEIG PK S2016A',
 'CPRPF 12 CLN&SF NEIG PK S2013A',
 'CPRPF 12 CLN&SF NEIG PK S2016B',
 'CPRPF 12 CLN&SF NEIG PK S2018A',
 'CPRPF 12 CLN&SF NEIG PK S2019B',
 'CPRPF 1992 GGP Irrigatn S1995B',
 'CPRPF 2000 NEIG REC&PK S2000C',
 'CPRPF 2000 NEIG REC&PK S2001B',
 'CPRPF 2000 NEIG REC&PK S2004A',
 'CPRPF COP MusicConcourseGarage',
 'CPRPF FC OSP VARS PK LRB-S2006',
 'CPRPF FC OSP VARS PK LRB-S2007',
 'CPRPF FC OSP VARS PK LRBS06&07',
 'CPSIF 2006 Prop 1B-City-08',
 'CPSIF 2006 Prop 1B-County-08',
 'CPSIF 2011 RD REPV&ST SFY-12C',
 'CPSIF 2011 RD REPV&ST SFY-13C',
 'CPSIF 2011 RD REPV&ST SFY-16E',
 'CPSIF 2014 TRPTN&RD IMP-2015B',
 'CPSIF 2014 TRPTN&RD IMP-2018B',
 'CPSIF 2014 TRTPN&RD IMP-2020B',
 'CPSIF 2014 TRTPN&RD IMP-2021C',
 'CPSIF ARRA',
 'CPSIF COP REFUNDING ST IMP2019',
 'CPSIF COP ST IMP Proj-2009B',
 'CPSIF COP ST IMP Proj-2012A',
 'CPSIF COP Street Repaving',
 'CPSIF COP Street Resurfacing',
 'CPSIF COP Streets & Curbramps',
 'CPSIF Octavia Blvd Special',
 'CPSIF Street Impvt-Fed',
 'CPSIF Street Impvt-Oth',
 'CPSIF Street Impvt-Sta',
 'CPSIF Street Impvt-Una',
 'CPXCF 10 EQ SFTY&EMY RE S2010E',
 'CPXCF 10 EQ SFTY&EMY RE S2012A',
 'CPXCF 10 EQ SFTY&EMY RE S2012E',
 'CPXCF 10 EQ SFTY&EMY RE S2013B',
 'CPXCF 10 EQ SFTY&EMY RE S2014C',
 'CPXCF 10 EQ SFTY&EMY RE S2016C',
 'CPXCF 14 EQ SFTY&EMY RE S2014D',
 'CPXCF 14 EQ SFTY&EMY RE S2016D',
 'CPXCF 14 EQ SFTY&EMY RE S2018C',
 'CPXCF 1500 Mission Project COP',
 'CPXCF 1500 Mission St. COP/CP',
 'CPXCF 16 PH & SFTY 1St S17A',
 'CPXCF 16 PH & SFTY 2nd S18E',
 'CPXCF 16 PH & SFTY 3rd S20D',
 'CPXCF 18 Emb SeawallGOB S2020A',
 'CPXCF 18 Emb SeawallGOB S2023B',
 'CPXCF 18 Emb SeawallGOB S2025A',
 'CPXCF 1997 Zoo Fac S2000B',
 'CPXCF 1997 Zoo Fac S2002A',
 'CPXCF 1997 Zoo Fac S2005H',
 'CPXCF 20 EQ SFTY&EMY RE S2021B',
 'CPXCF 20 EQ SFTY&EMY RE S2021E',
 'CPXCF 20 EQ SFTY&EMY RE S2025B',
 'CPXCF 20 HEALTH&RECOV S2021D',
 'CPXCF 20 HEALTH&RECOV S2023A',
 'CPXCF 2000 ACAMY OF SCI S2005E',
 'CPXCF 2008 SFGH IMP S2009A',
 'CPXCF 2008 SFGH IMP S2010A',
 'CPXCF 2008 SFGH IMP S2012D',
 'CPXCF 2008 SFGH IMP S2014A',
 'CPXCF 2008 SFGH IMP TAX S2010C',
 'CPXCF CFD Spcl Tax Bd S17A-TTC',
 'CPXCF CFD Spcl Tax Bd S19A-TTC',
 'CPXCF CFD Spcl Tax Bd S22A-TTC',
 'CPXCF COP CITY OFF BG S2007AB',
 'CPXCF COP Crit Reprs/Rcv Stmls',
 'CPXCF COP HOJ Relo-Site Aquis',
 'CPXCF COP HOJ Relo-Tenant Imp',
 'CPXCF COP WAR MEM VET BD S16A',
 'CPXCF COP WAR MEM VET BG S15AB',
 'CPXCF DPH 101Grove/1064Mis COP',
 'CPXCF Pub S Radio Repl Lease',
 'CPXCF TREASURE ISLD COP S2025B',
 'CPXCF WMVB COMMERCIAL PAPER',
 'CWP-Capital Projects Fund',
 'CWP-Debt Service Fund',
 'CWP-Operating Fund',
 'CWP-Operating Grants Fund',
 'Central Shops Fund',
 'Certificate of Participation Bond Fund',
 'Child Support Services',
 'Child Support Services Fund',
 'Child Support Trust Fund',
 'Children and Families Fund',
 "Children's Fund",
 'City Facilities Improvement Fund',
 'CleanPowerSF Capital Fund',
 'CleanPowerSF Operating Fund',
 'CleanPowerSF Operating Grants',
 'CleanPowerSF Special Revenue F',
 'CleanPowerSF Trust Agency Fund',
 'Cleanpowersf Operating Fund',
 'Cleanpowersf Special Revenue Fund',
 'Community Development Fund',
 'Community Health Services Fund',
 'Continuing Authority Ctrl',
 'Convention Facilities Fund',
 'Courts Deposits Fund',
 'Courts Deposits Fund-Interest',
 "Courts' Fund",
 'Culture & Recreation Fund',
 'Cwp-Trust & Agency Fund',
 'DA Pre-Forfeited Asset Accnts',
 'DNA Penalty Assess Gc 76104 7',
 'DPH HCSO',
 'DSCOP HOUSING TRUST FUND',
 'DSCOP Hope SF',
 'DSCOP MOSCONE CENTER S2013A',
 'DSCOP MOSCONE EXPANSION',
 'DSCOP REFDG -MOS S-N- S2011A-B',
 'DSCOP REFDG-JUVE HALL-S2014-R2',
 'DSCOP REFDG-OFF BLDG-S2015-R1',
 'DSCOP REFDG-SF CRTHSE-S2014-R1',
 'DSCOP REFUNDING S2010A',
 'DSCOP STREET IMPROVMT S2009B',
 'DSCOP STREET IMPROVMT S2012A',
 'DSCOP WAR MEML VTR BLDG S15AB',
 'DSGOB GENERAL OBLIGATION BOND',
 'DSGOB Loan Repmt for PASS S19A',
 'DSGOB SB1128 REV FOR LHH GOB',
 'DSGOB TSR FOR LHH GOB',
 'DSODS GENERAL CITY LOANS',
 'DSODS Pub S Radio Repl Lease',
 'DSODS Transbay Transit Ctr100M',
 'DSODS Transbay Transit Ctr160M',
 'DTIS-Telecomm. & Information S',
 'Deferred Pmt Settlement Fund',
 'Edison Schools',
 'Education Rev Augmentatn Fund',
 'Employees Retirement Trust',
 "Employees' Retirement System",
 'Environmental Protection Program Fund',
 'Fire Protection Systems Impvt. Fund',
 'Foster Care Rep Payee Fund',
 'GF Annual Account Ctrl',
 'GF Annual Authority Ctrl',
 'GF BSI-Continuing Project',
 'GF COVID STIMULUS FUND-FED',
 'GF Continuing Authority Ctrl',
 'GF Human Services Care',
 'GF Overhead-Recreation & Parks',
 'GF PW Work Order',
 'GF Work Order',
 'General Fund',
 'General Hopsital Operating Fund',
 'General Hospital Capital Projects Fund',
 'General Hospital Operating Grants Fund',
 'General Obligation Bond Fund',
 'General Services Fund',
 'Gift Fund',
 'Golf Fund',
 'Grants; NonProject; Cont Sta',
 'HHWP Special Revenue',
 'HHWP-Trust & Agency Fund',
 'HSS ADMIN GF SUPPORT FD',
 'HSS Dental Ben Trust Fund',
 'HSS Medical Ben Trust Fund',
 'HSS Non-Charter Benefits',
 'HSS Reserve',
 'Health Care-Prop B Trust Fund',
 'Hetch Hetchy Capital Projects Fund',
 'Hetch Hetchy Operating Fund',
 'Hetchy Capital Projects Fund',
 'Hetchy Debt Service Fund',
 'Hetchy Operating Fund',
 'Hetchy Operating Grants Fund',
 'Hlth Care-Prop B CC Trust Fund',
 'Human Welfare Fund',
 'IS-Central Shops Fund',
 'IS-Reproduction Fund',
 'Investment Earning Fund',
 'LHH - Patient Trust',
 'LHH Debt Service Fund',
 'LHH-Capital Projects Fund',
 'LHH-Operating Fund',
 'LHH-Operating Grants Fund',
 'LHH-Trust & Agency Fund',
 'Laguna Honda Capital Projects Fund',
 'Laguna Honda Debt Service Fund',
 'Laguna Honda Operating Fund',
 'Laguna Honda Operating Grants Fund',
 'Local Transportation Fund',
 'Low-Mod Income Housing Asset Fund',
 'Mission Rock 20% Set-aside',
 'Mission Rock 80% Facilities',
 'Mission Rock Dev ST Bd S2023A',
 'Mission Rock Impact Fee',
 'Mission Rock STD Dev Spcl Tax',
 'Moscone Convention Center Fund',
 'MsnRock Dev ST Bd S2021A-SRF',
 'MsnRock Dev ST Bd S2021B-SRF',
 'MsnRock Dev ST Bd S2021C-SRF',
 'MsnRock STD Dev Spcl Tx-SRF',
 'Muni Capital Projects Fund',
 'Muni Operating Fund',
 'Muni Operating Grants Fund',
 'Muni Special Revenue Fund',
 'Municipal Railway Improv Fund',
 'Neighborhood Development Fund',
 'OCII CFD 1',
 'OCII CFD 4',
 'OCII CFD 5',
 'OCII CFD 6',
 'OCII CFD 7',
 'OCII CFD 8',
 'OCII CFD 9',
 'Open Space & Park Fund',
 'Open Space & Park-Annual Proj',
 'Other Debt Service Fund',
 'Overhead Fund',
 'P70HistoricCore 20% set-aside',
 'P70HistoricCore 80% Facilities',
 'PUC Operating Fund',
 'Parking & Traffic Capital Projects Fund',
 'Parking & Traffic Gasoline Tax Fund',
 'Parking & Traffic Off-Street Parking Fnd',
 'Parking & Traffic Operating Fund',
 'Parking Off Street Parking Oper Fund',
 'Parking Operating Fund',
 'Pedestrian Operating Fund',
 'Perm ETF-Bequests',
 'Pier 70 20% set-aside',
 'Pier 70 80% Facilities',
 'Port Capital Projects Fund',
 'Port Operating',
 'Port Operating Fund',
 'Port South Beach Harbor Fund',
 'Port-Capital',
 'Port-South Beach Harbor',
 'Port-Trust And Agency',
 'Pub Admin-Pub Guard-Rep Payee',
 'Public Health State Rev Fund',
 'Public Library Fund',
 'Public Protection Fund',
 'Public Works, Transp. & Commerce Fund',
 'Real Property Fund',
 'Recreation & Park Capital Impvts Fund',
 'Redevelopment Debt Service Fund',
 'Redevelopment Obligation Fund',
 'Redevelopmnt Property Tax Fund',
 'Reproduction Fund',
 'Retiree Health Care Trust Fund - Prop B',
 'SA105-MR-Ofc Tax STD',
 'SA106-MR-Shoreline Tax STD',
 'SA107-Pier 70 Condo Tax STD',
 'SA108-P70 Leased PropTax STD',
 'SFCCD 2020 GOB S A TAX EX CAP',
 'SFCCD 2020 GOB S A-1 TAXA CAP',
 'SFCCD 2020 GOB S B',
 'SFCCD Educational-1999A',
 'SFCCD Educational-2000A',
 'SFCCD Tax & Rev Anticptn Notes',
 'SFCCD-General Fund',
 'SFCCD-Prop A Parcel Tax',
 'SFCCD-Restricted General Fund',
 'SFCCD-Retiree Health Care Fund',
 'SFGH-Capital Projects Fund',
 'SFGH-Operating Fund',
 'SFGH-Trust & Agency Fund',
 'SFIA-Capital Projects Fund',
 'SFIA-Debt Service Fund',
 'SFIA-Operating Fund',
 'SFIA-Operating Grants Fund',
 'SFIA-Special Revenue Fund',
 'SFIA-Trust & Agency Fund',
 'SFWD-Capital Projects Fund',
 'SFWD-Debt Service Fund',
 'SFWD-Operating Fund',
 'SFWD-Operating Grants Fund',
 'SFWD-Trust & Agency Fund',
 'SHF-10A Off-Duty Security Wk',
 'SR  Civil Service-Spec Rev',
 'SR 19 AFFORD HOUSING 1st S21A',
 'SR 19 AFFORD HOUSING 2nd S23C',
 'SR 19 AFFORD HOUSING 3rd S25C',
 'SR 2016 HOUS REHAB GO1st 2019A',
 'SR 2016 HOUS REHAB GO2nd 2020C',
 'SR 2016 HOUS REHAB GO3rd 2025E',
 'SR 2016 Prop E StreetTreeMaint',
 'SR 24 AFFORD HOUSING 1st S25D',
 'SR 30 Van Ness Building',
 'SR 555 Seventh St Building',
 'SR ADP Special Rev Fund',
 'SR Afford Housing Enforcement',
 'SR Afford Hsng Com Devlpmt COP',
 'SR Affordable Housing Bond-PI',
 'SR Affordable Housing GOB2016F',
 'SR Arts Com-Public Arts',
 'SR Arts Com-Strt Artist Prog',
 'SR Arts Comm-Art Enrichment',
 'SR BIF Operating Project',
 'SR BIF-Continuing Projects',
 'SR Balboa Park CI',
 'SR Building Standards Comssn',
 'SR Cable TV Access Dev&Prog',
 'SR Child Care Capital',
 'SR Child Support Offset Aid',
 'SR Cigarette Litter Abatement',
 'SR City Attorney-Special Rev',
 'SR City Hall TDRs',
 'SR Citywide Affordable Housing',
 'SR Comm Health-COVID Stim-FED',
 'SR Community Dev Revolvng Loan',
 'SR Community Health-Grants',
 'SR Community Health-Grants Oth',
 'SR Community Living',
 'SR Conv Fac Fd-Continuing',
 'SR Conv Fac Fd-Low Incm House',
 'SR Conv Fac Fd-Moscone Expan D',
 'SR Conv Fac Fd-Operating',
 'SR Court Dispute Resolution',
 'SR Courts Grants Cont Fed',
 "SR Courts' Spec Rev Fd-Annual",
 'SR Cultural Equity Endowment',
 'SR Culture & Rec Grants; A Fed',
 'SR Culture & Rec Grants; A Sta',
 'SR Culture & Rec Grants; C',
 'SR Culture & Rec Hotel Tax',
 'SR DA-Narc Forf&Asset Seizure',
 'SR DBI-Repair & Demolitions',
 'SR DNA Id Fund -Prop 69-2004',
 'SR DW-Special Engr Inspection',
 'SR Da-Special Revenue',
 'SR Development Agreement',
 'SR Dispute Resolution Program',
 'SR Downtown Neighborhood Prese',
 'SR Downtown Park',
 'SR Dvros Reimbursement',
 'SR ETF-Gift',
 'SR Eastern Neighborhood CI',
 'SR Env-Continuing Projects',
 'SR Env-Operating-Non-Project',
 'SR Facade Improvement Loan',
 'SR Gas Tax Annual Authority',
 'SR Gas Tax-Annually Budgeted',
 'SR Golf Fund -Continuing',
 'SR Golf Fund Annual',
 'SR Grantor For The Arts Fed',
 'SR Grants; ENV Continuing',
 'SR Grants; ENV Continuing Oth',
 'SR Grants; GSF Continuing',
 'SR Grants; GSF Continuing Oth',
 'SR Grants; GSF Continuing Sta',
 'SR HOPE SF COP 2nd',
 'SR Homeland Security',
 'SR Hope SF COP',
 'SR Hope SF CP Taxable',
 'SR Housing Program Fees',
 'SR Housing Trust COP',
 'SR Housing Trust Fund',
 'SR Human Welfare-Grants',
 'SR Human Welfare-Grants Oth',
 'SR Human Welfare-Grants Sta',
 'SR HumanWelfare-COVID Stim-FED',
 'SR Information Publication',
 'SR Library Fund - Continuing',
 'SR Library Grants; Cont Oth',
 'SR Library Grants; Cont Sta',
 'SR Library Special Revenue',
 'SR Low-mod Inc Housing NonBond',
 'SR Market & Octavia CI',
 'SR Mobed-Film Prod Sp',
 'SR Museums Admission',
 'SR Neighbor Dev-COVID Stim-FED',
 'SR Neighborhood Beautifcation',
 'SR Neighborhood Dev-Grants',
 'SR Neighborhood Dev-Grants Oth',
 'SR Neighborhood Dev-Grants Sta',
 'SR Nov 2016 Prop I Dignity',
 'SR OCOH Nov18 PropC GF Advance',
 'SR OCOH Nov18 PropCHomelessSvc',
 'SR Open Space&Park-Annual',
 'SR Open Space-Continuing',
 'SR Opioid Settlement Fund',
 'SR Other Special Revenue',
 'SR Outreach Fund - Prop J',
 'SR PPF Com Paper-SFPD Equipmt',
 'SR PW Paid Time Off',
 'SR PW-Const Inspection',
 'SR PW-Overhead',
 'SR PW-Personnel',
 'SR PW-Strong Motion Admin',
 'SR Planning Code Enforcement',
 'SR Police Law Enforcement Svcs',
 'SR Public Health',
 'SR Public Library Preserv',
 'SR Public Prot-COVID Stim-FED',
 'SR Public Protection-Grant',
 'SR Public Protection-Grant Oth',
 'SR Public Protection-Grant Sta',
 'SR R&P Maintenance Fund',
 'SR R&P-Fish&Game Propagation',
 'SR R&P-Marina -Annual',
 'SR R&P-Marina Yacht Harbor',
 'SR RMRA City Capital Funding',
 'SR RMRA County Capital Funding',
 'SR Real Property',
 'SR Real Property-General',
 'SR Rent Arbitration Board',
 'SR Residential Vacancy Tax',
 'SR Rincon Hill and SOMA CI',
 'SR Road',
 'SR Road - Annually Budgeted',
 'SR Road Annual Authority',
 'SR SFPD-Auto Fingerprint Id',
 'SR SFPD-County AutoWarrant Sys',
 'SR SFPD-Criminalistics Lab',
 'SR SFPD-NarcForf&AssetSeizure',
 'SR SFPD-Peace Offr Training',
 'SR SFPD-Vehicle Theft Crimes',
 'SR SOMA Developmnt Fee',
 'SR Seismic Safety GOB-2007A',
 'SR Seismic Safety GOB-2015A',
 'SR Seismic Safety Loan',
 'SR Seismic Safety-UMB Bonds',
 'SR Senior Citizens-Grants',
 'SR Senior Citizens-Grants Oth',
 'SR Senior Citizens-Grants Sta',
 'SR Services to Outside Agncy',
 'SR Sheriff-Inmate Program',
 'SR Sheriff-Peace Offr Traing',
 'SR Sheriff-State Authorized',
 'SR Small Business Assistance',
 'SR Solid Waste Non-Project',
 'SR Solid Waste Projects',
 'SR Special Gas Tax St Impvt',
 'SR State Auth Special Rev',
 'SR Surety Bond Self-Insurance',
 'SR TC Grants;Continuing',
 'SR TC Grants;Continuing Oth',
 'SR Tenants Overtime',
 'SR Traffic Congest Mitign Tax',
 'SR Traffic Offender',
 'SR Transit Center District',
 'SR Treasure Island IRFD 2022B',
 'SR Treasure Island IRFD 2023B',
 'SR Union Sq Prk, Rec, OS fee',
 'SR Van Ness & Market Infr',
 'SR Visitacion Valley CI',
 'SR Vital & Hlth Stat Fees',
 'SR WAR - Annual Authority Ctrl',
 'SR WAR Cont Authority Ctrl',
 'SR WOM Domestic Violence Prog',
 'SR War Mem Conssn Equip Rplm',
 'SR War Memorial Reserve',
 'SR War Memorial – Grants',
 'SR War Memorial-Operating',
 "SR Workers' Compensation",
 'SR Yerba Buena Gardens',
 'SRCTA ANNUAL ALLOCATION',
 'SRCTA SF COUNTY TRANSPRTN AGCY',
 'SRCTA Traffic Congest Mitign',
 'SSD 2016A Prop A Bond',
 'SSD 2016B Prop A Bond',
 'SSD 2016C Prop A Bond',
 'SSD 2024A Prop A Bond',
 'San Francisco Finance Corporation',
 'School District Agency Fund',
 'Self Insurance Fund',
 "Senior Citizens' Programs Fund",
 'Sheriff Deposits Fund',
 'South Beach Harbor Fund',
 'Sp Tx Dist 2009-1 -Sf Sustnble',
 'Street Improvement Fund',
 'Sustainable Streets',
 'TI CFD IA#1 Special Tax Fund',
 'TI CFD IA#2 Special Tax Fund',
 'TI CFD IA#3 Special Tax Fund',
 'TI Continuing Authority Ctrl',
 'TI IRFD Facility Bond S2022A',
 'TI IRFD Facility Bond S2023A',
 'TI IRFD Housing Bond S2022B',
 'TI IRFD Housing Bond S2023B',
 'TI IRFD Incrmt Tax Prj Housing',
 'TI IRFD IncrmtTax Prj Facility',
 'Tax Collector Deposits Fund',
 'Tax Collector State Rev Fund',
 'Taxi Commission Operating Fund',
 'Telecomm. & Information Svcs Fund',
 'Transbay CFD ST Bd S2022A',
 'Transbay CFD ST Pay-go Fund',
 'Transit',
 'Transportation & Commerce Fund',
 'Trial Courts Agency Fund',
 'USD - Interest Accumulation',
 'USD - Subsidiary Control Fund',
 'USD01 - General Fund',
 'USD05 - County School Services',
 'USD14 - Deferred Maintenance',
 'USD21 building fund',
 'USD21-90380_1997SchoolBond-03B',
 'USD21-90380_1997SchoolBond-97A',
 'USD21-90390_2003SchoolBond-03E',
 'USD21-90391_2006SchoolBond-06A',
 'USD21-90391_2006SchoolBond-06B',
 'USD21-90391_2006SchoolBond-06C',
 'USD21-90391_2006SchoolBond-06D',
 'USD21-90391_2006SchoolBond-06E',
 'USD21-90391_2006SchoolBond-06F',
 'USD21-90392_2011SchoolBond-11B',
 'USD21-90392_2011SchoolBond-11C',
 'USD21-90392_2011SchoolBond-11D',
 'USD25 - Capital Facilities',
 'USD30-StateSchoolBldg-LeasePur',
 'USD35-County School Facilities',
 'USD40 - Capital Outlay Fund',
 'USD49_SchoolFacSaftey Tax',
 'USD51-Bond Int & Redemption',
 'USD63 - Enterprise Fund -KALW',
 'USD67 - Self-Insurance Fund',
 'Unapportioned Property Taxes',
 'War Memorial Fund',
 'Wastewater Capital Projects Fund',
 'Wastewater Operating Fund',
 'Wastewater Operating Grants Fund',
 'Water Capital Projects Fund',
 'Water Operating Fund',
 nan}

In [19]:
len(set(funds_counter))

561

### Checking Null values of column 'Fund Category Code'

In [20]:
df_cp1['Fund Category Code']

0         5.0
1         5.0
2         4.0
3         5.0
4         4.0
         ...
378723    1.0
378724    1.0
378725    1.0
378726    2.0
378727    1.0
Name: Fund Category Code, Length: 378728, dtype: float64

Has many Null values

In [21]:
lib.tools.hasnull(df_cp1['Fund Category Code'])

2052     NaN
4319     NaN
5778     NaN
10697    NaN
15167    NaN
15197    NaN
18947    NaN
19736    NaN
20223    NaN
111481   NaN
113201   NaN
114072   NaN
116332   NaN
317199   NaN
318221   NaN
337693   NaN
340975   NaN
348603   NaN
350430   NaN
355736   NaN
356697   NaN
359095   NaN
Name: Fund Category Code, dtype: float64

I feel this should be an int. Let's check.

In [22]:
lib.tools.values_counter(df_cp1['Fund Category Code'])

Counter({1.0: 181999,
         3.0: 86614,
         5.0: 33584,
         2.0: 26772,
         4.0: 22859,
         0.0: 20834,
         6.0: 5989,
         7.0: 55,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1,
         nan: 1})

They should be ints. Filling Nulls with 0 (no code for 0) and casting column to int.

In [23]:
df_cp1['Fund Category Code'] = df_cp1['Fund Category Code'].fillna(0).astype(int)
df_cp1['Fund Category Code']

0         5
1         5
2         4
3         5
4         4
         ..
378723    1
378724    1
378725    1
378726    2
378727    1
Name: Fund Category Code, Length: 378728, dtype: int64

Verifying we've updated null values

In [24]:
lib.tools.hasnull(df_cp1['Fund Category Code'])

Series([], Name: Fund Category Code, dtype: int64)

### Checking Null values for column 'Fund Category'

In [25]:
df_cp1['Fund Category']

0         Work Orders/Overhead
1         Work Orders/Overhead
2                       Grants
3         Work Orders/Overhead
4                       Grants
                  ...
378723               Operating
378724               Operating
378725               Operating
378726         Annual Projects
378727               Operating
Name: Fund Category, Length: 378728, dtype: object

In [26]:
lib.tools.hasnull(df_cp1['Fund Category'])

2052      NaN
4319      NaN
5778      NaN
10697     NaN
15167     NaN
15197     NaN
18947     NaN
19736     NaN
20223     NaN
111481    NaN
113201    NaN
114072    NaN
116332    NaN
317199    NaN
318221    NaN
337693    NaN
340975    NaN
348603    NaN
350430    NaN
355736    NaN
356697    NaN
359095    NaN
Name: Fund Category, dtype: object

In [27]:
fund_category_counter = lib.tools.values_counter(df_cp1['Fund Category']).keys()

In [28]:
set(fund_category_counter)

{'Annual Projects',
 'Annual Projects - Authority Control',
 'Continuing Projects',
 'Continuing Projects - Account Control',
 'Continuing Projects - Authority Control',
 'Continuing Projects - Project Control',
 'Grants',
 'Grants Projects',
 'Operating',
 'Unspecified',
 'Work Orders/Overhead',
 nan}

### Filling 'Fund' and 'Fund Category' with appropriate filler values

In [29]:
unfixed_null_columns = ['Fund', 'Fund Category']
for column in unfixed_null_columns:
    df_cp1.loc[:, column], _filler_values = lib.tools.fillnull(df_cp1[column])
df_cp1[unfixed_null_columns]

                       Fund         Fund Category
0       Muni Operating Fund  Work Orders/Overhead
1       Muni Operating Fund  Work Orders/Overhead
2                 Gift Fund                Grants
3              General Fund  Work Orders/Overhead
4             Bequests Fund                Grants
...                     ...                   ...
378723         General Fund             Operating
378724         General Fund             Operating
378725         General Fund             Operating
378726         General Fund       Annual Projects
378727         General Fund             Operating

[378728 rows x 2 columns]

### Verifying if we have anymore nulls

In [30]:
log.info(lib.tools.data_err_rate(df_cp1))
log.info(lib.tools.hasnull(df_cp1))

0.0
Empty DataFrame
Columns: []
Index: []

# Checking and Validating data

## Creating backup

In [31]:
df_cp2 = df_cp1.copy()

In [32]:
df_cp2.columns

Index(['Fiscal Year', 'Revenue or Spending', 'Related Govt Unit',
       'Organization Group Code', 'Organization Group', 'Department Code',
       'Department', 'Program Code', 'Program', 'Character Code', 'Character',
       'Object Code', 'Object', 'Sub-object Code', 'Sub-object',
       'Fund Type Code', 'Fund Type', 'Fund Code', 'Fund',
       'Fund Category Code', 'Fund Category', 'Budget', 'data_as_of',
       'data_loaded_at'],
      dtype='object')

In [33]:
importlib.reload(lib)
lib.tools.values_counter_info(df_cp2)

Fiscal Year: <int64> BEGIN
	2015: 14095
	2016: 14215
	2017: 14736
	2018: 39647
	2021: 29759
	2019: 26882
	2020: 29983
	2022: 28396
	2023: 28949
	2024: 28524
	2025: 28268
	2026: 18220
	2027: 9367
	2010: 13231
	2011: 13401
	2012: 13299
	2013: 13752
	2014: 14004
Fiscal Year: <int64> END

Revenue or Spending: <object> BEGIN
	Spending: 314570
	Revenue: 64158
Revenue or Spending: <object> END

Related Govt Unit: <object> BEGIN
	Spending: 314570
	Revenue: 64158
Related Govt Unit: <object> END

Organization Group Code: <int64> BEGIN
	2: 131244
	5: 40488
	6: 84671
	4: 36309
	3: 36512
	1: 45873
	7: 3631
Organization Group Code: <int64> END

Organization Group: <object> BEGIN
	Public Works, Transportation & Commerce: 131244
	Culture & Recreation: 40488
	General Administration & Finance: 84671
	Community Health: 36309
	Human Welfare & Neighborhood Development: 36512
	Public Protection: 45873
	General City Responsibilities: 3631
Organization Group: <object> END

Department Code: <object> BEGIN
Department Code: Has more than 20 values (69 values)

Department: <object> BEGIN
Department: Has more than 20 values (120 values)

Program Code: <object> BEGIN
Program Code: Has more than 20 values (383 values)

Program: <object> BEGIN
Program: Has more than 20 values (361 values)

Character Code: <object> BEGIN
Character Code: Has more than 20 values (98 values)

Character: <object> BEGIN
Character: Has more than 20 values (80 values)

Object Code: <object> BEGIN
Object Code: Has more than 20 values (783 values)

Object: <object> BEGIN
Object: Has more than 20 values (699 values)

Sub-object Code: <object> BEGIN
Sub-object Code: Has more than 20 values (3557 values)

Sub-object: <object> BEGIN
Sub-object: Has more than 20 values (2974 values)

Fund Type Code: <object> BEGIN
Fund Type Code: Has more than 20 values (36 values)

Fund Type: <object> BEGIN
Fund Type: Has more than 20 values (30 values)

Fund Code: <object> BEGIN
Fund Code: Has more than 20 values (566 values)

Fund: <object> BEGIN
Fund: Has more than 20 values (561 values)

Fund Category Code: <int64> BEGIN
	5: 33584
	4: 22859
	1: 181999
	3: 86614
	2: 26772
	0: 20856
	6: 5989
	7: 55
Fund Category Code: <int64> END

Fund Category: <object> BEGIN
	Work Orders/Overhead: 33584
	Grants: 6682
	Operating: 181999
	Continuing Projects: 12922
	Annual Projects: 4968
	Not Available: 22
	Continuing Projects - Authority Control: 73692
	Continuing Projects - Project Control: 5989
	Grants Projects: 16177
	Unspecified: 20834
	Annual Projects - Authority Control: 21804
	Continuing Projects - Account Control: 55
Fund Category: <object> END

Budget: <int64> BEGIN
Budget: Has more than 20 values (102205 values)

data_as_of: <object> BEGIN
	2025/08/31 10:07:35 PM: 378728
data_as_of: <object> END

data_loaded_at: <object> BEGIN
	2025/09/01 02:03:23 AM: 378728
data_loaded_at: <object> END

## 'date_as_of' and 'data_loaded_at' are just a single Timestamp. Can drop these columns

In [34]:
df_cp2 = df_cp2.drop(['data_as_of', 'data_loaded_at'], axis=1)

# Beginning Cleaning Process
## Creating backup

In [35]:
df_cp3 = df_cp2.copy()

## Creating valid list

In [36]:
valid = [
    'Revenue or Spending',
    'Related Govt Unit',
    'Organization Group',
    'Fund Category Code'
]

In [37]:
df_cp3.columns

Index(['Fiscal Year', 'Revenue or Spending', 'Related Govt Unit',
       'Organization Group Code', 'Organization Group', 'Department Code',
       'Department', 'Program Code', 'Program', 'Character Code', 'Character',
       'Object Code', 'Object', 'Sub-object Code', 'Sub-object',
       'Fund Type Code', 'Fund Type', 'Fund Code', 'Fund',
       'Fund Category Code', 'Fund Category', 'Budget'],
      dtype='object')

## Checking '*_Code' columns

In [38]:
df_cp3['Department Code'].unique()

array(['MTA', 'REC', 'ASR', 'DPH', 'FAM', 'LLB', 'CFC', 'ADM', 'HRD',
       'TTX', 'ART', 'LIB', 'PUC', 'DPW', 'HHP', 'AIR', 'DBI', 'SHF',
       'AAM', 'PDR', 'FIR', 'CHF', 'JUV', 'PAB', 'BOS', 'CAT', 'SCI',
       'CWP', 'WTR', 'PRT', 'RET', 'CII', 'CRT', 'POL', 'ECN', 'DSS',
       'ADP', 'DAT', 'ENV', 'HOM', 'ECD', 'WOM', 'HRC', 'MYR', 'RNT',
       'CON', 'GEN', 'TIS', 'UNA', 'REG', 'CSS', 'ETH', 'HSS', 'CPC',
       'CLP', 'WAR', 'USD', 'CSC', 'DPA', 'HSA', 'DEM', 'BOA', 'CCD',
       'SDA', 'DEC', 'SAS', 'CTA', 'GNL', 'TJP'], dtype=object)

In [39]:
for col, series in df_cp3.items():
    if 'Code' in col:
        log.info(f'{col}')
        log.info(f'\t{series.value_counts()}')
        log.info(f'{col}\n')

Organization Group Code
	Organization Group Code
2    131244
6     84671
1     45873
5     40488
3     36512
4     36309
7      3631
Name: count, dtype: int64
Organization Group Code

Department Code
	Department Code
DPW    41336
DPH    36309
PUC    28563
MTA    24589
ADM    21786
       ...
SDA      201
CLP       75
CTA       22
TJP        3
GNL        1
Name: count, Length: 69, dtype: int64
Department Code

Program Code
	Program Code
OPR      157150
CAP       46016
CAPCP     12763
ADMIN     11930
RCVY       9854
          ...
EEU           2
ECE           1
CBA           1
AMS           1
BCL           1
Name: count, Length: 383, dtype: int64
Program Code

Character Code
	Character Code
MAND_FRING_BEN       63883
NON_PERS_SVCS        53191
013                  36394
SALARIES             30453
021                  22566
                     ...
SPCL_ITEMS_OUT           2
890                      2
UNAP_REV_CHRT_RSV        1
EXTRA_ITEM_GAIN          1
45C                      1
Name: count, Length: 98, dtype: int64
Character Code

Object Code
	Object Code
HLTH_SVC             20314
081                  17877
OTH_FR_BEN           14302
PERM_SAL_MISC        13310
PROF_SPEC_SVC        13095
                     ...
495006                   1
FAC_MNTC_BUD_CFWD        1
598042                   1
598041                   1
803                      1
Name: count, Length: 783, dtype: int64
Object Code

Sub-object Code
	Sub-object Code
nan       131072
01701       3880
01402       3833
00101       3760
01401       3755
           ...
445302         1
460704         1
495046         1
460205         1
465854         1
Name: count, Length: 3557, dtype: int64
Sub-object Code

Fund Type Code
	Fund Type Code
GEN_FUND            88635
ENT_FUND            67175
SP_REV              66895
1G                  59477
2S                  29662
CPTL_PRJ            18143
INTRL_SRVC           6479
5A                   5738
5W                   5008
5M                   4602
6I                   3896
5H                   3232
PSN_OTHR_EMP_BEN     2841
5P                   2765
5C                   2130
5T                   2067
5N                   1596
5L                   1453
INVEST_TRST_FUND     1029
7P                    766
AGNCY_FUNDS           764
7S                    601
CMPNT_UNTS            556
5X                    550
7E                    545
5O                    495
DEBT_SRVC             446
8A                    328
PERMA_FUND            202
7A                    168
3C                    120
5Y                    109
5Q                     75
4D                     73
7R                     65
5Z                     42
Name: count, dtype: int64
Fund Type Code

Fund Code
	Fund Code
1GAGF                   58579
GEN_FUND~10000          45526
GEN_FUND~10020          19896
GEN_FUND~10060           9980
ENT_FUND~MTA_TRANSIT     9614
                        ...
AGNCY_FUNDS~28610           1
SP_REV~10576                1
SP_REV~12490                1
AGNCY_FUNDS~28940           1
SP_REV~14360                1
Name: count, Length: 566, dtype: int64
Fund Code

Fund Category Code
	Fund Category Code
1    181999
3     86614
5     33584
2     26772
4     22859
0     20856
6      5989
7        55
Name: count, dtype: int64
Fund Category Code

### We don't need the code columns because they are just the code to their respective columns. Dropping them.

In [40]:
codes_columns = [col for col in df_cp3.columns if 'Code' in col]
codes_columns

['Organization Group Code',
 'Department Code',
 'Program Code',
 'Character Code',
 'Object Code',
 'Sub-object Code',
 'Fund Type Code',
 'Fund Code',
 'Fund Category Code']

In [41]:
df_cp3 = df_cp3.drop(codes_columns, axis=1)

In [42]:
df_cp3

,Fiscal Year,Revenue or Spending,Related Govt Unit,Organization Group,Department,Program,Character,Object,Sub-object,Fund Type,Fund,Fund Category,Budget
0,2015,Spending,Spending,"Public Works, Transportation & Commerce",Municipal Transportation Agency,Agency Wide Expenses,Services of Other Depts,Services of Other Depts (AAO Funds),TIS-SFGTV Services (AAO),MTA Municipal Railway Funds,Muni Operating Fund,Work Orders/Overhead,60447
1,2015,Spending,Spending,"Public Works, Transportation & Commerce",Municipal Transportation Agency,"Security, Safety, Training & Enforcement",Mandatory Fringe Benefits,Health Service,Health Service-City Match,MTA Municipal Railway Funds,Muni Operating Fund,Work Orders/Overhead,31292
2,2016,Spending,Spending,Culture & Recreation,Recreation and Park Commission,Golden Gate Park,Mandatory Fringe Benefits,Social Security,Social Security (OASDI & HI),Expendable Trust Funds,Gift Fund,Grants,3388
3,2016,Spending,Spending,Culture & Recreation,Recreation and Park Commission,Golden Gate Park,Mandatory Fringe Benefits,Social Security,Social Security - Medicare (HI Only),General Fund,General Fund,Work Orders/Overhead,1323
4,2016,Spending,Spending,Culture & Recreation,Recreation and Park Commission,Golden Gate Park,Materials & Supplies,Materials & Supplies Budget Only,Materials & Supplies-Budget,Expendable Trust Funds,Bequests Fund,Grants,89127
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378723,2012,Spending,Spending,General Administration & Finance,Mayor,Neighborhood Services,Materials & Supplies,Other Materials & Supplies,Other Office Supplies,General Fund,General Fund,Operating,4000
378724,2012,Spending,Spending,General Administration & Finance,Mayor,Public Policy & Finance,Mandatory Fringe Benefits,Health Service,Health Service-City Match,General Fund,General Fund,Operating,56225
378725,2012,Spending,Spending,General Administration & Finance,Controller,Payroll And Personnel Services,Materials & Supplies,Other Materials & Supplies,Forms,General Fund,General Fund,Operating,50000
378726,2012,Spending,Spending,General Administration & Finance,Controller,Payroll And Personnel Services,Non Personnel Services,Professional & Specialized Services,Other Professional Services,General Fund,General Fund,Annual Projects,871993
378727,2012,Spending,Spending,General Administration & Finance,Controller,Payroll And Personnel Services,Salaries,Overtime,Overtime - Misc,General Fund,General Fund,Operating,15000

# Final Cleaned Dataset

In [43]:
df_clean_data = df_cp3.copy()

In [44]:
lib.export_data(filename, df_clean_data)

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/san_francisco_budget/san_francisco_budget_CLEAN.csv')