In [1]:
import re
import importlib
import requests
import datetime
import json
from pathlib import Path

from tqdm import tqdm
import pandas as pd
import numpy as np

import lib


importlib.reload(lib)

log = lib.getLogger(Path().cwd().name)
working_directory = Path().cwd()
export_clean_directory = working_directory / 'clean'

In [2]:
categories_path = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/goodreads/clean/my_books_categories_CLEAN.csv'
export_categories_path = '/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/goodreads/clean/my_books_categories.csv'

In [3]:
df = lib.read_data(categories_path)

PortfolioLogger.lib.tools: INFO: Encoding: utf-8
PortfolioLogger.lib.tools: INFO: Stripping whitespaces from my_books_categories_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function read_data at 0x10d436980> took 0.055 secs to complete.

In [4]:
df

      Unnamed: 0   Book Id                     Category
0              0  18400112  Language Arts & Disciplines
1              1  62047984  Language Arts & Disciplines
2              2  58416952                      Fiction
3              3  58416952                 High Fantasy
4              4  58416952             Series:Hierarchy
...          ...       ...                          ...
3765        3765  43848929               Social Science
3766        3766  43848929                    Strangers
3767        3767  43848929          Threat (Psychology)
3768        3768  43848929                        Trust
3769        3769  30141085  Language Arts & Disciplines

[3770 rows x 3 columns]

In [9]:
categories = df['Category'].unique().tolist()

In [10]:
len(categories)

2032

In [11]:
categories

['Language Arts & Disciplines',
 'Fiction',
 'High Fantasy',
 'Series:Hierarchy',
 'Fantasy',
 'Fantasy Fiction',
 'General',
 'Action & Adventure',
 'Genius',
 'Science Fiction',
 'Gifted Persons',
 'Hallucinations And Illusions',
 'Multiple Personality',
 'Short Stories',
 'Abuelos (Hombres)',
 'Aptitudes Motoras',
 'Bibliotecarios',
 'Bibliothécaires',
 "Children'S Fiction",
 'Clumsiness',
 'Cuentos Humorosos',
 'Etc. Pour La Jeunesse',
 'Grandfathers',
 'Grandparents',
 'Grands-Pères',
 'Humorous Stories',
 'Juvenile Fiction',
 'Juvenile Fiction / Action & Adventure / General',
 'Juvenile Fiction / Fantasy & Magic',
 'Librarians',
 'Maladresse',
 'Materiales En Español',
 'New York Times Bestseller',
 'Nouvelles',
 'Novela Fantástica',
 'Novela Juvenil',
 'Romans',
 'English Literature',
 'Fiction / Fantasy / Action & Adventure',
 'Fiction / Fantasy / Epic',
 'Grail',
 'Quests (Expeditions)',
 'Vampires',
 'Dark Fantasy',
 'Epic',
 'Geographical Myths',
 'Historical',
 'Imaginary Places',
 'Imaginary Wars And Battles',
 'Kings And Rulers',
 'Magic',
 'Prophets',
 'Sci-Fi & Fantasy',
 'Revenge',
 'Adaptations',
 'Blessing And Cursing',
 'Cours Et Courtisans',
 'Courts And Courtiers',
 'Fairies',
 'Fantasy & Magic',
 'Fées',
 'Love & Romance',
 'Series:A Court Of Thorns And Roses',
 'Adult',
 'Humor',
 'Series:Secret Projects',
 'Time Travel',
 'Crime',
 'Mystery',
 'Mystery Thriller',
 'Novella',
 'Psychological Thriller',
 'Suspense',
 'Thriller',
 'American Literature',
 'Accessible Book',
 'American Fantasy Fiction',
 'Betrayal',
 'Bien Y Mal',
 'Civil War',
 'Dragons',
 'Epic Fantasy',
 'Epic Fiction',
 'Epic Literature',
 'Family',
 'Fantastic Fiction',
 'Feudalism',
 'Ficción',
 'Folk Healers',
 'Forced Marriage',
 'Good And Evil',
 'Guerra Civil',
 'Guerras Imaginarias',
 'Hugo Award Winner',
 'Ignotus Award Winner',
 'Incest',
 'Intrigue',
 'Invierno',
 'Knights',
 'Locus Award Winner',
 'Loyalty',
 'Moral Ambiguity',
 'Novela',
 'Overdrive',
 'Penal Colonies',
 'Persistent Vegetative States',
 'Politics',
 'Protected Daisy',
 'Reyes Y Soberanos',
 'Royalty And Nobility',
 'Seasons',
 'Series:A Song Of Ice And Fire',
 'Seven Kingdoms (Imaginary Place)',
 'Supernatural',
 'Trial By Combat',
 'Vengeance',
 'Voyages And Travels',
 'Walls',
 'War And Conflict',
 'Wights',
 'Winter',
 '1905-1997',
 '1939-1945',
 'Aspect Psychologique',
 'Aspectos Psicológicos',
 'Austria',
 'Autobiography',
 'Biografía',
 'Biografías',
 'Biographies',
 'Biography',
 'Camps De Concentration',
 'Collected Works',
 'Concentration Camp Inmates',
 'Concentration Camps',
 'Correspondence',
 'Counseling',
 'Drama',
 'Erlebnisbericht',
 'Existential Psychology',
 'Existential Psychotherapy',
 'Existentialism',
 'Existentialisme',
 'Existentiell Psykoterapi',
 'Fen Xi Xin Li Xue',
 'Frankl',
 'Freedom Of Choice',
 'Förintelsen',
 'German',
 'German Prisoners And Prisons',
 'Guerre Mondiale',
 'Holocaust',
 'Holocaust - Personal Narratives',
 'Holocaust - Study & Teaching',
 'Holocaust Biographies',
 'Holocauste',
 'Holocausto',
 'Individual Psychologists',
 'Internal Medicine',
 'Jewish (1939-1945)',
 'Jewish (1939-1945) Fast (Ocolc)Fst00958866',
 'Jing Shen Fen Xi',
 'Judío (1939-1945)',
 'Kapo',
 'Koncentrationsläger',
 'Konzentrationslager',
 'Livets Mening',
 'Logoterapi',
 'Logoterapia',
 'Logotherapie',
 'Logotherapy',
 'Logothérapie',
 'Meaning (Psychology)',
 'Meaning Of Life',
 'Narrativas Personales',
 'Nazi Concentration Camp Inmates',
 'Nazi Concentration Camps',
 'Organization & Administration',
 'Pathological Psychology',
 'Personal Narratives',
 'Prison Psychology',
 'Prisoners And Prisons',
 'Prisonniers',
 'Prisonniers Et Prisons Des Allemands',
 'Prisons',
 'Psicoterapia',
 'Psychiatrie',
 'Psychiatrists & Psychologists - Biography',
 'Psychoanalysis And Philosophy',
 'Psychoanalytic Therapy',
 'Psychological Aspects',
 'Psychological Aspects Of Concentration Camps',
 'Psychological Aspects Of Holocaust',
 'Psychologie',
 'Psychologists',
 'Psychologues',
 'Psychology',
 'Psychotherapy',
 'Psykologiska Aspekter',
 'Recits Personnels',
 'Récits Personnels',
 'Sens (Philosophie)',
 'Shoah',
 'Significación (Psicología)',
 'Social Psychology',
 'Spirituality',
 'Viktor Emil',
 'War',
 'World War',
 'X',
 'Family Life',
 'Religious',
 'Visionary & Metaphysical',
 'Alcoholism',
 'Horror',
 'Horror Fiction',
 'Large Print Books',
 'Large Type Books',
 'Middle-Aged Men',
 'Occult Fiction',
 'Paranormal Fiction',
 'Psychic Ability',
 'Psychics',
 'Suspense Fiction',
 'Authors',
 'Backstories',
 'Boys',
 'Cabin Fever',
 'Caretakers',
 'Clairvoyance',
 'Colorado',
 'Demonology',
 'Extrasensory Perception',
 'Families',
 'Fiction - Horror',
 'Fiction / Horror',
 'Ghost Fiction',
 'Ghosts',
 'Gothic & Horror',
 'Haunted Houses',
 'Horror & Ghost Stories',
 'Horror - General',
 'Horror Tales',
 'Hotelkeepers',
 'Hotels',
 'Jack (Fictitious Character)',
 'Military History',
 'Occult & Supernatural',
 'Occultism',
 'Paranormal Fiction Suspense & Thriller',
 'Plays',
 'Precognition',
 'Property',
 'Psychological',
 'Roque',
 'Strategy',
 'Supernatural Thrillers',
 'Telepathy',
 'Thrillers',
 'Topiary',
 'Torrance',
 'Amitié',
 'Artificial Intelligence',
 'British And Irish Fiction (Fictional Works By One Author)',
 'Dystopian',
 'Electronic Books',
 'Fiction / Literary',
 'Fiction / Science Fiction / General',
 'Fiction / Visionary & Metaphysical',
 'Friendship',
 'Intelligence Artificielle',
 'Literary',
 'Love',
 'Paid Companions (Household Employees)',
 'Robots',
 'Romance Fiction',
 'Speculative Fiction',
 'The Future',
 'Adventure',
 'Brandon Sanderson',
 'Coming-Of-Age',
 'Female Protagonist',
 'Healing',
 'Hope',
 'Self-Discovery',
 'Spiritual Journey',
 'Young Adult',
 'Action And Adventure',
 'Colonies Spatiales',
 'Epidemics',
 'Space And Time',
 'Space Colonies',
 'Women Authors',
 'Écrivaines',
 'College Teachers',
 'Fiction / Thrillers / Psychological',
 'Fiction / Thrillers / Suspense',
 'Greek Mythology',
 'Murderers',
 'Psychotherapists',
 'Secret Societies',
 'Teacher-Student Relationships',
 'Truthfulness And Falsehood',
 'University Of Cambridge',
 'Women Psychotherapists',
 'Bibliothèques',
 'Choice (Psychology)',
 'Choix (Psychologie)',
 'Decision Making',
 'Fiction / Science Fiction / Time Travel',
 'Fiction / Women',
 'Future Life',
 'Libraries',
 'New York Times Reviewed',
 'Prise De Décision',
 'Regret',
 'Vie Future',
 'Alien Contact',
 'Chinese Science Fiction',
 'Extraterrestrial Beings',
 'Fiction / Science Fiction / Alien Contact',
 'Fiction / Science Fiction / Hard Science Fiction',
 'Hard Science Fiction',
 'Human-Alien Encounters',
 'Survival',
 'Adulto',
 'Covert Operations',
 'Fantasía',
 'Magia',
 'Mystical Powers',
 'Nobility',
 'Slaves',
 'Thieves',
 'Upraising',
 'Women Revolutionaries',
 'Modern Fiction',
 'Cours Et Courtisans -- Romans',
 'Courts And Courtiers -- Fiction',
 'Etc',
 'Good And Evil -- Fiction',
 'Imaginary Places -- Fiction',
 'Lieux Imaginaires -- Romans',
 'Magic -- Fiction',
 'Sieges',
 'Sieges -- Fiction',
 'SièGes (Histoire) -- Romans',
 'Idaho',
 'Istanbul (Turkey)',
 'Medieval',
 'Multiple Timelines',
 'Space',
 'Contemporary',
 'Paranormal',
 'Biography & Autobiography',
 'Amerikanisches Englisch',
 'Art',
 'Artistas',
 'Artistes',
 'Artists',
 'Auto-Realización',
 'Bildungsromans',
 'Chang Pian Xiao Shuo',
 'Coming Of Age',
 'Fiction / Coming Of Age',
 'Fiction / Psychological',
 'Goldfinch',
 'Jeunes Hommes',
 'Jóvenes (Varones)',
 'Loss (Psychology)',
 'New York (N.Y.)',
 'Perte (Psychologie)',
 'Pintores',
 'Pérdida (Psicología)',
 'Rich People',
 'Roman',
 'Réalisation De Soi',
 'Self-Acceptance',
 'Self-Realization',
 'Spanish Language Materials',
 'Transitional Objects (Psychology)',
 'Young Men',
 'Astronautes',
 'Astronauts',
 'End Of The World',
 'Fiction / Science Fiction / Action & Adventure',
 'Fin Du Monde',
 'Habiletés De Survie',
 'Hard Sci-Fi',
 'Hard Science-Fiction',
 'Memory Disorders',
 'Sci-Fi',
 'Science-Fiction',
 'Shipwrecks',
 'Space Flight',
 'Survival After Airplane Accidents',
 'Vol Spatial',
 'Accounting',
 'Attitude Change',
 'Business & Economics',
 'Consumption (Economics)',
 'Ethics',
 'Finance',
 'Financial Literacy',
 'Investing',
 'Management',
 'Money',
 'Personal',
 'Personal Finance',
 'Quality Of Life',
 'Richesse',
 'Satisfaction',
 'Self-Help Techniques',
 'Wealth',
 'Series:Stormlight Archive',
 'Dystopia',
 'Abuse',
 'Addiction',
 'Brain',
 'Clinical Medicine',
 'Combat',
 'Diseases',
 'Evidence-Based Medicine',
 'Health & Fitness',
 'Körpererfahrung',
 'Medical',
 'Mental Health',
 'Mind And Body',
 'Neurology',
 'Neuroplasticity',
 'Neuroscience',
 'Neurowissenschaften',
 'Physical Violence Recovery',
 'Physiopathology',
 'Post-Traumatic',
 'Post-Traumatic Stress Disorder',
 'Post-Traumatic Stress Disorder (Ptsd)',
 'Posttraumatisches Stresssyndrom',
 'Psychic Trauma',
 'Psychisches Trauma',
 'Psychotherapie',
 'Sexual Abuse',
 'Sexual Trauma',
 'Stress Disorders',
 'Therapie',
 'Therapy',
 'Traitement',
 'Trauma Survivors',
 'Traumatisme Psychique',
 'Treatment',
 'Veterans',
 'Violence',
 'État De Stress Post-Traumatique',
 'Bénédiction Et Malédiction',
 'City And Town Life',
 'Klątwa',
 'Princes',
 'Princesses',
 'Vie Urbaine',
 'Wojna',
 'Climate',
 'Décadence',
 'Fiction / Humorous / General',
 'Fiction / Satire',
 'Interpersonal Relations',
 'Life On Other Planets',
 'Maladies À Virus',
 'Plague',
 'Regression (Civilization)',
 'Resilience (Personality Trait)',
 'Résilience (Trait De Personnalité)',
 'Virus Diseases',
 '813/.54',
 'African American',
 'African American Women',
 'African Americans',
 'African Americans--Fiction',
 'Apocalyptic & Post-Apocalyptic',
 'Audiobooks',
 'Black Teenage Girls',
 'California',
 'Comic Books',
 'Comics & Graphic Novels',
 'Comics & Graphic Novels / Historical Fiction',
 'Comics & Graphic Novels / Science Fiction',
 'Dystopias',
 'Environmental Disasters',
 'Faith',
 'Graphic Novels',
 'Ps3552.U827 P37 2000',
 'Strips',
 'Twenty-First Century',
 'Twenty-First Century--Fiction',
 'Women',
 'Social Science',
 'Fiction / Action & Adventure',
 'Fiction / Fantasy / General',
 'Revolutions',
 'Buddhism',
 'Conduct Of Life',
 'Doctrines',
 'Happiness',
 'Hinduism',
 'Monastic And Religious Life',
 'Self-Help',
 'Abridged Audio - Misc. Nonfiction',
 'Ambição',
 'Business',
 'Control (Philosophy)',
 'Control (Psychology)',
 'Contrãole (Psychologie',
 'Contrôle (Psychologie)',
 'Contrôle (Psychologie.)',
 'Gesellschaft',
 'History & Theory - General',
 'Influência',
 'Jogo',
 'Leadership',
 'Liderança',
 'Macht',
 'Manipulação',
 'Motivational',
 'Nonfiction',
 'Nutzung',
 'Personal Growth',
 'Persuasão',
 'Philosophy And Ethics',
 'Poder',
 'Political Science',
 'Political Science & Theory',
 'Political Science / History & Theory',
 'Politics/International Relations',
 'Pouvoir (Morale)',
 'Pouvoir (Morale.)',
 'Power (Philosophy)',
 'Power (Psychology)',
 'Power (Social Sciences)',
 'Self-Improvement',
 'Success',
 'Zwischenmenschliche Beziehung',
 'Chess',
 'End Games',
 'Games & Activities',
 'Attachment Behavior',
 'Family & Relationships',
 'Intimacy (Psychology)',
 'Combinaties',
 'Games',
 'Schaken',
 'Coffee',
 'Forgiveness',
 'Loss',
 'Magical Realism',
 'Redemption',
 'Romance',
 'Second Chances',
 'Slice-Of-Life',
 '1961-1975',
 'Communists',
 'Espionage',
 'Soldiers',
 'Vietnam',
 'Vietnam War',
 'War & Military',
 '1954-',
 'Clonage',
 'Cloning',
 'Cloning--Fiction',
 'De Tissus',
 'Donation Of Organs',
 "Donneurs D'Organes",
 "Dons D'Organes",
 'England',
 'Etc--Fiction',
 'Femmes',
 'Fic',
 'Human Cloning',
 'Ishiguro',
 'Kazuo',
 'Literature',
 'Novela Inglesa',
 'Organ Donors',
 'Organ Donors--Fiction',
 'Powieść Angielska',
 'Pr6059.S5 N48 2006',
 'Psychological Fiction',
 'Reminiscing',
 'School Children',
 'Tissues',
 'Tłumaczenia Polskie',
 'Women--Fiction',
 '1000Blackgirlbooks',
 '2005',
 'African American & Black',
 'African American Children',
 'African American Families',
 'African American Teenage Girls',
 'Brothers And Sisters',
 'Christian',
 'Girls',
 'Hurricane Katrina',
 'Hurricane Katrina (2005) Fast (Ocolc)Fst01755264',
 'Mississippi',
 'Motherless Families',
 'Natural Disasters',
 'Poor',
 'Poverty',
 'Reading Level-Grade 10',
 'Reading Level-Grade 11',
 'Reading Level-Grade 12',
 'Reading Level-Grade 7',
 'Reading Level-Grade 8',
 'Reading Level-Grade 9',
 'Rural Poor',
 'Siblings',
 'Teenagers',
 'American Fiction',
 'American Fiction (Fictional Works By One Author)',
 'Drug Traffic',
 'Policía',
 'Sheriffs',
 'Tesoros Ocultos',
 'Texas',
 'Treasure Troves',
 'Treasure-Trove',
 'Tráfico De Drogas',
 'Afghanistan',
 'Afghanistan-Konflikt',
 'Afghans',
 'Amistad Entre Hombres',
 'Amitié Masculine',
 'Arabic Fiction',
 'Autographed Books',
 'Bacha Bazi',
 'Betrayal--Fiction',
 'Boys--Fiction',
 'Brass Knuckles',
 'Clases Sociales',
 'Classes Sociales',
 'Competitions',
 'Fiction Subjects',
 'Fictional Works',
 'Fictional Works [Publication Type]',
 'Fighter Kites',
 'Freundschaft',
 'Garçons',
 'Hazaras',
 'Histoire',
 'Historical Fiction',
 'In Library',
 'Junge',
 'Kites',
 'Literary Fiction',
 'Littérature Américaine',
 'Long Now Manual For Civilization',
 'Male Friendship',
 'Male Friendship--Fiction',
 'Modern & Contemporary Fiction (Post C 1945)',
 'Muchachos',
 'Mullahs',
 'Novelas Afganas',
 'Open Library Staff Picks',
 'Open Syllabus Project',
 'Parent And Child',
 'Pashtuns',
 'Sadistic Personality Disorder',
 'Social Class',
 'Social Classes',
 'Social Classes&#X200B;',
 'Social Classes--Fiction',
 'Social Conditions',
 'Soviet-Afghan War',
 'Soziale Ungleichheit',
 'Talibans',
 'Teenage Boys',
 'Trahison (Morale)',
 'Traición',
 'Translations Into Persian',
 'World Literature',
 'Early Retirement',
 'Ensamhet',
 'Ensamstående Män',
 'Feelgood',
 'Grannar',
 'Humoristiska Skildringar',
 'Humorous',
 'Jubilación Anticipada',
 'Neighborhoods',
 'Neighbors',
 'Novel',
 'Older Men',
 'Parasuicide',
 'Pensionärer',
 'Retirees',
 'Romaner',
 'Single Men',
 'Självmordsförsök',
 'Suicidal Behavior',
 'Svensk Skönlitteratur',
 'Svensk Skönlitteratur: Romaner Och Noveller',
 'Translation',
 'Vecinos',
 'Viudos',
 'Vänskap',
 'Widowers',
 'Air Pilots',
 'Series:Skyward',
 'Survival Stories',
 'Young Adult Fiction',
 'Brigands And Robbers',
 'Justice',
 'Rebellion',
 'Aristocracy (Social Class)',
 'Atonement',
 'Brothers',
 'Chr 2004',
 'Classic Literature',
 'Conditions Sociales',
 'Continental European Fiction (Fictional Works By One Author)',
 'Dictionaries',
 'English Fiction',
 'English Language',
 'Epileptics',
 'Fathers And Daughters',
 'Fiction In English',
 'Frères',
 'History',
 'Idiot (Television Program)',
 'Pro Gotham Book Mart (Former Owner) (Gotham Book Mart Collection Copy)',
 'Pères Et Filles',
 'Russia',
 'Russia In Fiction',
 'Russian Fiction',
 'Russian Literature',
 'Sanatoriums',
 'Social Life And Customs',
 'Television Adaptations',
 'Translations',
 'Translations From Russian',
 'Translations Into English',
 'Triangle (Relations Humaines)',
 'Triangles (Interpersonal Relations)',
 'Épileptiques',
 'Художественная Литература -- Российская Федерация -- Русская Литература -- 2-Ая Пол. 19 В. -- Романы',
 'American Poetry',
 'Body',
 'Mind & Spirit',
 'Peace Of Mind',
 'Religious Aspects',
 'Religious Life',
 'Spiritual Life',
 'Suffering',
 'Cooking',
 'Cooking Methods',
 'Reference',
 'Regional & Ethnic Cooking',
 'Drowning',
 '& Magic',
 'A Wrinkle In Time',
 'Adventure And Adventurers',
 'Age:Max:14',
 'Age:Min:10',
 'Award:Newbery Award',
 'Classics',
 'Espacio Y Tiempo',
 'Friendship In Adolesce',
 'Gifted Children',
 'Grade:Max:Undefined',
 'Grade:Min:Kindergarten And Up',
 'Juvenile Fiction - Classics',
 'Lexile Range:701-800',
 'Lexile:740',
 'Missing Persons',
 'Moral And Ethical Aspects',
 'Murry Family (Fictitious Character)',
 'Murry Family (Fictitious Characters)',
 'Newbery Medal',
 'Newbery Medal Books',
 'Picture Books',
 'Poopnce',
 'Responsibility',
 'Spanish: Young Adult (Gr. 10-12)',
 'Tiểu Thuyết',
 'Viaje En El Tiempo',
 'Văn Học Mĩ',
 'Acculturation',
 "Américains D'Origine Asiatique",
 "Américains D'Origine Coréenne",
 'Asian & Asian American',
 'Asian Americans',
 'Autobiographies',
 'Bereavement',
 'Biography & Memoir',
 'Chagrin',
 'Chanteurs',
 'Cultural',
 'Death',
 'Essays & Narratives',
 'Ethnic & Regional',
 'Food Memoir & Travel',
 'Grief',
 'Group Identity',
 'Humans',
 'Identité Collective',
 'Japanese Breakfast (Musical Group)',
 'Korean',
 'Korean Americans',
 'Koreans',
 'Mother And Child',
 'Mother-Child Relations',
 'Mothers And Daughters',
 'Musiciens Rock',
 'Mère Et Enfant',
 'Mères Et Filles',
 'Republic Of Korea',
 'Rock Musicians',
 'Singers',
 'Social Identification',
 'United States',
 'American',
 'American Science Fiction',
 'American Short Stories',
 'Asteroids',
 'Cognitive Dissonance',
 'Collections & Anthologies',
 'Computers',
 'Frankenstein Complex',
 'Heisenbugs',
 'High Tech And Hard Science Fiction',
 'Human-Robot Relations',
 'Hyperspace',
 'Morality',
 'Positronic Brains',
 'Readers',
 'Readers (Secondary)',
 'Robopsychology',
 'Robotics',
 'Robots In Fiction',
 'Selenium',
 'Shahada',
 'Smear Campaigns',
 'Space Stations',
 'Space-Based Solar Power',
 'Supercomputers',
 'Three Laws Of Robotics',
 'Hari Seldon (Fictitious Character)',
 'Historians',
 'Prophecy',
 'Psychohistoire',
 'Psychohistory',
 'Vie Extraterrestre',
 'Fiction / Fantasy / Dragons & Mythical Creatures',
 'Knights And Knighthood',
 'Medieval Kings And Rulers',
 'Monarchy',
 'Royal Houses',
 'Succession',
 'Westeros (Imaginary Place)',
 '2001-02',
 "Al'Thor Rand (Fictitious Character)",
 'American Fantasy',
 "Children'S Stories",
 'Fantasy .',
 'Monsters',
 "Rand Al'Thor (Fictitious Character)",
 'Reader Recommended',
 'Series:The Wheel Of Time',
 'Detective And Mystery Stories',
 'Drug Abuse',
 'Impostors And Imposture',
 'Narcotic Habit',
 'Pasadena (Calif.)',
 'Police',
 'Stories Without Words',
 'Actors',
 'Canadian Fiction',
 'Collection:Canada Reads',
 'Collection:Canada Reads 2023',
 'Fiction / Science Fiction / Adventure',
 'Shakespearean Actors And Actresses',
 'Symphonies',
 'Traveling Theater',
 'Cruise Ships',
 'Fiction / Mystery & Detective / Traditional',
 'Fraud',
 'Mystery & Detective',
 'Mystery Fiction',
 'Ponzi Schemes',
 'Finnish Epic Poetry',
 'History And Criticism',
 'Kalevala',
 'Magicians',
 'Slavery',
 'Authorship',
 'Biographers',
 'Calif.)',
 'Hollywood (Los Angeles',
 'Lgbtq Novels',
 'Man-Woman Relationships',
 'Motion Picture Actors And Actresses',
 'Motion Picture Industry',
 'Women Journalists',
 'American Poets',
 "Américaines D'Origine Asiatique",
 'Asian American Women',
 'Biography & Autobiography / Cultural',
 'Ethnic & Regional / Asian & Asian American',
 'Ethnic Relations',
 'Literary Criticism / American',
 'Poets',
 'Poètes Américains',
 'Social Science / Ethnic Studies / American / Asian American Studies',
 'Women Poets',
 'Anachronism',
 'Arthur (Fictitious Character)',
 'Arthur (Fictitious Character) Fiction',
 'Arthur Dent (Fictitious Character)',
 'Bird Language',
 'Dent',
 'Ford (Fictitious Character)',
 'Ford (Fictitious Character) Fiction',
 'Ford Prefect (Fictitious Character)',
 'Heart Of Gold',
 'Infinite Improbability Drive',
 'Interplanetary Voyages',
 'Interstellar Travel',
 'Paradoxes',
 'Prefect',
 'Reverse Engineering',
 'Sofas',
 'Space-Time Eddy',
 'The Ashes',
 'Trilogy Of Five',
 'Wikkit Gate',
 'Xenophobia',
 'Armand (Fictitious Character)',
 'Armand (Fictitious Character) -- Fiction',
 'Armand (Personnage Fictif) -- Romans',
 'Armand Gamache (Fictitious Character)',
 'Gamache',
 'Livres En Gros CaractèRes',
 'Police -- Queì¹Bec (Province) -- Fiction',
 'Police Procedural',
 'Quebec (Province)',
 'Victimes De Violence -- Romans',
 'Victims Of Violent Crimes',
 'Victims Of Violent Crimes -- Fiction',
 'Gay Men',
 'Gays',

In [25]:
counts = df['Category'].value_counts()
counts

Category
Fiction                        129
General                         80
New York Times Bestseller       77
Language Arts & Disciplines     74
Fantasy                         49
                              ...
Selenium                         1
Robots In Fiction                1
Robotics                         1
Robopsychology                   1
Trust                            1
Name: count, Length: 2032, dtype: int64

In [21]:
len(counts)

Index(['Fiction', 'General', 'New York Times Bestseller',
       'Language Arts & Disciplines', 'Fantasy', 'Science Fiction',
       'Nouvelles', 'Romans', 'Large Type Books', 'Fantasy Fiction',
       ...
       'Supercomputers', 'Space-Based Solar Power', 'Space Stations',
       'Smear Campaigns', 'Shahada', 'Selenium', 'Robots In Fiction',
       'Robotics', 'Robopsychology', 'Trust'],
      dtype='object', name='Category', length=2032)

In [22]:
i = 0
top = {}
for i, (col, item) in enumerate(counts.items()):
    top[col] = item
    if i == 100:
        break

In [23]:
top

{'Fiction': 129,
 'General': 80,
 'New York Times Bestseller': 77,
 'Language Arts & Disciplines': 74,
 'Fantasy': 49,
 'Science Fiction': 38,
 'Nouvelles': 34,
 'Romans': 32,
 'Large Type Books': 26,
 'Fantasy Fiction': 25,
 'New York Times Reviewed': 24,
 'Action & Adventure': 20,
 'Magic': 20,
 'English Literature': 19,
 'Epic': 18,
 'American Literature': 18,
 "Children'S Fiction": 17,
 'Reading Level-Grade 11': 17,
 'Reading Level-Grade 12': 17,
 'Open Library Staff Picks': 16,
 'Long Now Manual For Civilization': 16,
 'Ficción': 15,
 'Novela': 15,
 'Psychological': 14,
 'Thrillers': 14,
 'Historical': 13,
 'Literary': 13,
 'Friendship': 13,
 'Reading Level-Grade 10': 13,
 'Juvenile Fiction': 12,
 'Imaginary Places': 12,
 'Adventure': 11,
 'Reading Level-Grade 9': 11,
 'Good And Evil': 11,
 'Literature': 11,
 'Psychology': 11,
 'Survival': 11,
 'British And Irish Fiction (Fictional Works By One Author)': 10,
 'Roman': 10,
 'American Science Fiction': 9,
 'Suspense': 9,
 'Interpersonal Relations': 9,
 'Imaginary Wars And Battles': 9,
 'Psychological Fiction': 9,
 'Fiction / Literary': 9,
 'History And Criticism': 8,
 'Horror': 8,
 'War': 8,
 'History': 8,
 'Young Adult Fiction': 8,
 'Biography': 8,
 'Biography & Autobiography': 8,
 'Dystopian': 8,
 'Suspense Fiction': 7,
 'Thriller': 7,
 'Time Travel': 7,
 'Reading Level-Grade 8': 7,
 'Family Life': 7,
 'Missing Persons': 7,
 'Amerikanisches Englisch': 7,
 'American Fiction': 7,
 'Dragons': 7,
 'Spanish Language Materials': 7,
 'Short Stories': 6,
 'American Fantasy Fiction': 6,
 'Reading Level-Grade 7': 6,
 'Mystery & Detective': 6,
 'Fictional Works': 6,
 'English Fiction': 6,
 'Crime': 6,
 'English Language': 6,
 'Dune (Imaginary Place)': 6,
 'Revenge': 6,
 'Death': 6,
 'Etc. Pour La Jeunesse': 6,
 'Adventure And Adventurers': 6,
 'Comic Books': 6,
 'Strips': 6,
 'Families': 6,
 'Mystery Fiction': 5,
 'Drama': 5,
 'Classics': 5,
 'Fiction In English': 5,
 'Classic Literature': 5,
 'Brothers And Sisters': 5,
 'Historical Fiction': 5,
 'Adaptations': 5,
 'Extraterrestrial Beings': 5,
 'Novela Fantástica': 5,
 'American Fiction (Fictional Works By One Author)': 5,
 'Fiction / Fantasy / Epic': 5,
 'Conduct Of Life': 5,
 'Self-Help': 5,
 'Love': 5,
 'Biographies': 5,
 'Police': 5,
 'Humor': 5,
 'Travel': 4,
 'Horror Tales': 4,
 'Coming Of Age': 4,
 'New York (N.Y.)': 4}

In [46]:
to_remove = [
    'Fiction',
    'General',
    'New York Times Bestseller',
    'Language Arts & Disciplines',
    'Romans',
    'Large Type Books',
    'New York Times Reviewed',
    'Reading Level-Grade 11',
    'Reading Level-Grade 12',
    'Open Library Staff Picks',
    'Long Now Manual For Civilization',
    'Ficción',
    'Novela',
    'Reading Level-Grade 10',
    'Reading Level-Grade 9'
] + counts[counts == 1].index.tolist()
to_remove

['Fiction',
 'General',
 'New York Times Bestseller',
 'Language Arts & Disciplines',
 'Romans',
 'Large Type Books',
 'New York Times Reviewed',
 'Reading Level-Grade 11',
 'Reading Level-Grade 12',
 'Open Library Staff Picks',
 'Long Now Manual For Civilization',
 'Ficción',
 'Novela',
 'Reading Level-Grade 10',
 'Reading Level-Grade 9',
 'Regression (Psychology)',
 'Whales In Literature',
 'Academic Literacy',
 'Father Time (Symbolic Character)',
 'Whales',
 'Achab (Personnage Fictif)',
 'Shipwreck Survival',
 '813/.3',
 'Regression',
 'Freedom',
 'Whalers (Persons)',
 'Walfang',
 'Symbolism',
 'Adventure Fiction',
 'Television Personalities',
 'Political Corruption',
 'Zhang Pian Xiao Shuo',
 'Whales--Fiction',
 'Whaling',
 'William',
 'Whaling In Literature',
 'Shipwrecks--Fiction',
 'Whaling Ships',
 'Whaling Ships--Fiction',
 'Whaling--Fiction',
 'Performing Arts / Comedy',
 'Sweden',
 'Syllabi',
 'Relationships',
 'Shipwreck',
 'Ahab',
 'Captain (Fictitious Character)--Fiction',
 'Ship Captains--Fiction',
 'Herman)',
 'Naufragios',
 'Moby Dick (Melville',
 'Captain (Fictitious Character)',
 'Moby Dick',
 'Mentally Ill--Fiction',
 'Literatura Infantil',
 'Illustrations',
 'Fate And Fatalism',
 'Novela Psicológica',
 'Enfermos Mentales',
 'Racially Mixed People',
 'Drama (Dramatic Works By One Author)',
 'Cuentos De Mar',
 'Comics & Graphic Novels / Literary',
 'Comics & Graphic Novels / General',
 'Chasse',
 'Capitanes De Barcos',
 'Capitaines De Navire',
 'American Adventure Stories',
 'Romance Literature',
 'Ship Captains',
 'Sea Stories',
 'Captain Ahab (Fictitious Character)',
 'Sailors--Fiction',
 'Sailors',
 'American Sea Stories',
 'Récits De Mer',
 'Baleines',
 'Personnes Vivant Avec Un Trouble De Santé Mentale',
 'Readers (Primary)',
 'Ps2384.M6 M45 1992',
 'Ps2384 .M6 2001C',
 'Prohibition',
 'Picture-Writing In Literature',
 'Pictorial Works',
 'Ballenas',
 'South Africa',
 'Vietnam Conflict',
 'Heaven',
 'Buried Treasure',
 'Relations Humaines',
 'Sciences Cognitives',
 'Teoría De Las',
 'Utopies',
 'Utopian Fiction',
 'Technology',
 'Technologie',
 'Réalité Virtuelle',
 'Puzzles',
 'Jeux Intellectuels',
 'Vocabulary',
 'Mars (Planet)',
 'Toma De Decisiones',
 'Space Warfare--Fiction',
 'Space Warfare -- Fiction',
 'Space Vehicles',
 'Seres Extraterrestres',
 'Sat (Educational Test)',
 'Romance Ingles',
 'Pr5774 .W3 2005Dx',
 'Outer Space',
 'Martians',
 'Recovery',
 'Virtual Reality',
 'Grandes Puissances',
 'Great Powers',
 'Education',
 'Explorers In Fiction',
 'Intuición',
 'Intuicíon',
 'Explorers',
 'Discovery And Exploration',
 'Discoveries In Geography In Fiction',
 'Discoveries In Geography',
 'Intuition',
 'Christopher Columbus In Fiction',
 'America In Fiction',
 'Intuïtie',
 'Jugement (Logique)',
 'Pensée',
 'Dune (Lieu Imaginaire)',
 'Ponderación Y Decisión',
 'Prise De Décision (Psychologie)',
 'Prise De Décision (Relations Humaines)',
 'Philippines',
 'Filipino Americans',
 'Americans',
 'Mars (Planet) -- Fiction',
 'Invasions',
 'Hour-Glasses',
 'Automation',
 'Humor / Essays',
 'Ender (Fictitious Character)',
 'Data Processing',
 'Child Soldiers',
 'Bean (Fictitious Character : Card)',
 'Battle School (Imaginary Place)',
 'Humor / Form / Essays',
 'Humor / Topic / Cultural',
 'Award:Hugo Award=1986',
 'Außerirdische Intelligenz',
 'Aliens',
 'Imaginary Wars And Battles--Fiction',
 'Time',
 'Mothers And Sons',
 'Tiempo',
 'Temps',
 'Moral Conditions',
 'Métis',
 'Specimens',
 'Sabliers',
 'Performing Arts',
 'Rédemption',
 'Ender Wiggin (Fictitious Character)',
 'Hegemony',
 'Hermanos',
 'Krieg',
 'Imaginary Wars And Battles In Literature',
 'Apartheid',
 'Biography & Autobiography / Personal Memoirs',
 'Guerra Espacial',
 'Guerra',
 'Ficcion',
 'Earth',
 'Aladdin (Legendary Character)',
 '823.912',
 'Wiggin',
 'War Games',
 'The Ender Quintet',
 'Comedians',
 'Science-Fiction-Literatur',
 'Prize:Nebula',
 'Comedy',
 'Peter Wiggin (Fictitious Character)',
 'Comiques',
 'Military Education',
 'Military Art And Science',
 'Maniobras De Guerra',
 'Outlines',
 '1911-1993',
 'Vedettes De Télévision',
 'Lokalne Volitve',
 'Englisch',
 'Elections',
 'Elecciones Locales',
 'Country Life',
 'Ciudades Y Pueblos',
 'City Council Members',
 'Hunger',
 'Black Humor (Literature)',
 'Филологические Науки. Художественная Литература -- Великобритания -- Английская Литература -- С 1945 Г. -- Произведения Художественной Литературы -- Художественная Проза -- Романы. Повести. Рассказы -- Фантастические И Мистические Романы',
 'Рассказы. Романы Ужасов',
 'Повести',
 'Post-Apocalyptic Fiction',
 'The Lord Of The Rings',
 'Terre Du Milieu (Lieu Imaginaire)',
 'Quête',
 'Pr6039.O32 L6 2005',
 'Middle Earth (Imaginary Place)--Fiction',
 'Media Tie-In',
 'Lord Of The Rings (Tolkien',
 'J.R.R.)',
 'Hobbits (Personnages Fictifs)',
 'Local Elections',
 'Občinski Svetniki',
 'Facsimiles',
 'Fathers And Sons--Fiction',
 'English Manuscripts',
 'English Authors',
 'Dystopias In Literature',
 'Dystopian Plays',
 'Distopías',
 'Disasters',
 'Cult Of Personality',
 'Correspondence..',
 'Contemporary Fiction',
 'Extinction Event',
 'Censorship',
 'Father-Son Relationship',
 'Cautionary Tales And Verse',
 'Fathers And Sons',
 'Authors And Publishers',
 'Authoritarianism',
 'Fathers And Sons Fiction; Fiction Dystopian; Fiction Science Fiction General; American Fiction (Fict',
 'Življenje Na Podeželju',
 'Vida Urbana',
 'V Leposlovju',
 'Smrt',
 'Hobbits (Fictitious Characters)',
 'Gift Books',
 'Regression (Civilization)--Fiction',
 'Gandalf (Fictitious Character)',
 'Assertiveness',
 'Self-Esteem',
 'Aprobación De Sí Mismo',
 'Amor A Sí Mismo (Psicología)',
 'Yale University',
 'Women College Students',
 'Zombies',
 'Applied Psychology',
 'War Correspondents',
 'Oral History',
 'Interpersonal Communication',
 'Correspondants De Guerre',
 'Language Arts & Disciplines / Communication',
 'Totalitarismus',
 'Miscellanea',
 'Spanish Fiction',
 'Strangers',
 'Science-Fiction Anglaise',
 'Science And State',
 'Realism In Literature',
 'Threat (Psychology)',
 'Australia',
 'Assertiveness (Psychology)',
 'Courage',
 'Ficción Fantástica Inglesa',
 'Frodo Baggins (Fictitious Character)',
 'Road Fiction',
 'Robinsonades',
 'Survival Skills',
 'Voyages And Travels--Fiction',
 'Alibi',
 'Criminal Evidence',
 'Frodo (Fictitious Character)',
 'Frodo',
 'Psychological Horror',
 'Morale',
 'Rape Victims',
 'Shapeshifters',
 'Bilbo (Fictitious Character)',
 'Baggins',
 'Family Violence',
 '823/.912',
 'Risk',
 'Fiction / Thrillers / General',
 'Psychotherapy Patients',
 'English Political Fiction',
 'Fiction Classics',
 'Islands',
 'Ps3537.A426 C315 1991',
 'Juvenile Works',
 'J.D.)',
 'J. D. (Jerome David)',
 'Bibliography',
 'Holden Caulfield (Fictitious Character)',
 'Holden Acaulfield (Fictitious Character)',
 'Holden (Personnage Fictif)',
 'Holden (Fictitious Character)--Fiction',
 'Holden (Fictitious Character)',
 'Heranwachsender',
 'Governors',
 'Garçons Adolescents Dans La Littérature',
 'Fictional Works Publication Type',
 'Engelsk Skönlitteratur',
 'Emotionally Disturbed Teenage Boys',
 'Cleveland (Ohio)',
 'Caulfield',
 'Catcher In The Rye (Salinger',
 'Book: Sga Sal',
 'American Young Adult Fiction',
 'Domestic Fiction',
 'Preparatory Schools',
 'Runaway Teenagers',
 'Futurology',
 'Runaway Teenagers In Literature',
 'Interpersonal Relations In Children',
 'Human Relations',
 'Golding',
 'Etc.',
 'Employees',
 'Childhood',
 'Castaways',
 'Officials And Employees',
 'Castaway',
 'Presidents',
 'Airplane Crash Survival',
 'Protection',
 'Secret Service',
 'United States. Secret Service',
 'Time Travel In Fiction',
 'Adoption',
 'Universidad Sergio Arboleda',
 'Teenage Boys In Literature',
 'Salinger',
 'Runaway Teenagers--Fiction',
 'Asian American',
 'Alienation In Teenagers',
 'Adolescents Fugueurs Dans La Littérature',
 'Adolescence In Literature',
 'Adolescence',
 'Motherhood',
 'Sentimental Fiction',
 'Single Mothers',
 'Novelas Inglesas',
 'Novela Política',
 "Woman'S Fiction",
 'Nineteen Eighty-Four (Orwell',
 'Newspeak',
 'Nationalism',
 'Middle Aged Men',
 'Memory Holes',
 'Apocalypse',
 'Apocalyptic Fiction',
 'Lexicography',
 'Language & Literary Studies',
 'Insurance Agents',
 'Ingsoc',
 'Civilization',
 'Indic Fiction (English)',
 'Historical Negationism',
 'George)',
 'Outer Party',
 'Perpetual War',
 'Politique',
 'Totalitarianism And Literature',
 '813.5 S 3-8',
 '1991',
 '1919-2010',
 'Zukunft',
 'Translations Into Urdu',
 'Translating And Interpreting',
 'Dometic Fiction',
 'Totalitarismo',
 'Totalitarianism--Fiction',
 'Thoughtcrime',
 'Polizeistaat',
 'Telescreens',
 'Surveillance',
 'Suburban Life',
 'Sting Operations',
 'Interracial Adoption',
 'Satirical Literature',
 'Resistance Movements',
 'Rebels',
 'Pr6029.R8 N49 2003',
 'Spanish Discovery And Exploration',
 'Hq734 .G7136 1999Bx',
 'Caring',
 'Homeless Persons',
 'Homeless Persons--Family Relationships--New York (State)--New York',
 'Homeless Persons--New York (State)--New York--Family Relationships',
 'Detective',
 'Corruption',
 'Computer Hackers Sweden Stockholm Fiction',
 'Comparative Literature',
 'Clase Alta',
 'Hv5132 .W35 2005',
 'Child Sexual Abuse',
 'Itinérance',
 'Book Of Leviticus',
 'Belletristische Darstellung',
 'Aufklärung <Kriminologie>',
 'Jeannette',
 'Aufklärung',
 'Aristocracy',
 '21St Century Film And Literature',
 'Jeunesse (Biographie)',
 'Tráfico De Seres Humanos',
 'Translations From Swedish',
 'Thrillers & Mystery',
 'Homeless Persons--Family Relationships',
 'Hijos De Padres Alcohólicos',
 'Junge Frau',
 'Hijos De Padres Alcoho Licos',
 'Journalists Sweden Stockholm Fiction',
 'Journalistes',
 'Journalist',
 "Journalisme D'Enquête",
 'Famille Dysfonctionnelle',
 'Investigative Reporting',
 'Familles Inadaptées',
 'Investigate',
 'Internet Archive Wishlis',
 'Family Memoirs - Biography',
 'Industrialists',
 'Family Relations',
 'Heiresses',
 'Gender And Violence',
 'Family Relationships',
 'Fiction: Literature',
 'Faschismus',
 'General & Miscellaneous Biography',
 'Hijos De Alcohólicos',
 'Familie',
 'Enquêtes',
 'Patient Narratives',
 'Periodistas',
 'Periodical Editors',
 'Mystery And Suspense Stories',
 'Public Affairs & Policies',
 'Spanish: Adult Fiction',
 'Skjønnlitteratur',
 'Relaciones De Familia',
 'Secuestro',
 'Political Theology',
 'Relaciones Familiares',
 'Polar Bears',
 'Relations Familiales',
 'Sans-Abri',
 'Parry',
 'Orphans',
 'Novela Fantástica Inglesa',
 'Niños',
 'Mädchen',
 'Missing Persons -- Fiction',
 'Social Work & Human Services',
 'Missing Persons -- Experiments -- Juvenile Fiction',
 'Missing Persons -- Experiments',
 'Merveilleux',
 'Menschenversuch',
 'Teachers',
 'Teens',
 'The Marvelous',
 'Editores',
 'Pauvres',
 'Pauvreté',
 'Italian Fiction',
 'Personas Sin Hogar',
 'Investigación',
 'Human Trafficking',
 'Pobres',
 'Gritty',
 'Esclavitud',
 'Detectives',
 'Uncles',
 'Pobreza',
 'Poor--West Virginia--Welch--Biography',
 'Problem Families',
 'Computadoras',
 'Asesinato',
 'Problemas Familiares',
 'Zigeuner',
 'Will Parry (Fictitious Character)',
 'Will (Personaje Literario)',
 'Famille',
 'Kriminalfall',
 'Développement Personnel',
 'Textbooks For Foreign Speakers',
 'Child Of Impaired Parents',
 'Temples',
 'Children Of Alcoholics',
 'Study And Teaching',
 'Stoker',
 'Romanians',
 'Children Of Alcoholics--United States--Biography',
 'Romania',
 'Children Of Alcoholics--West Virginia--Welch--Biography',
 'Desamparados',
 'Rhetoric',
 'Religion',
 'Document',
 'Legends',
 'Irish Fiction',
 'Irish Authors',
 'Horror Stories',
 'Gothic Literature',
 'Gothic',
 'Ghost',
 'Film And Video Adaptations',
 'Casos De Estudio',
 'Vampires In Literature',
 'Familias Problemáticas',
 'Vampiros',
 'Warfare',
 'Solitude',
 'Récits De Guerre Américains',
 'Politicians',
 '2000S',
 'Futuristic Fiction',
 'Nouvelles Américaines',
 'Minnesota',
 'Military Personnel',
 'Loneliness',
 '362.82/092 B',
 'Adult Children',
 'Biografi A.',
 'Guerre Du Viêt-Nam',
 'Biographie',
 'Anciens Combattants',
 'American War Stories',
 'Cas',
 'Women Sleuths',
 'Policières',
 'Case Studies',
 'Dysfunctional Families',
 'Dysfunctional Families--United States--Case Studies',
 'Epistolary Novels',
 'English Horror Tales',
 'Sexueller Missbrauch',
 'Sex',
 'Enfance Et Jeunesse',
 'Schwedisch',
 'Scandinavian Comparative Literature',
 'Rich',
 'Reading Materials',
 'Rape',
 "Enfant D'Alcoolique",
 'Enfant De Parents Alcooliques',
 'Punk',
 "Enfants D'Alcooliques",
 'Familias',
 'Missing Persons Investigation Sweden Oland Fiction',
 'Familias Problema Ticas',
 'Misogyny',
 'Mikael Blomkvist (Fictitious Character)',
 'Mikael Blomkvist',
 'Lisbeth',
 'Kriminalroman',
 'Kriminalliteratur',
 'Swedish Fiction',
 'Tattooing',
 'Text',
 'British',
 'Dracula I Litteraturen',
 'Dracula (Stoker)',
 'Dracula (Stoker',
 'Dysfunctional Families--West Virginia--Welch--Case Studies',
 'Dracula (Personaje Literario)',
 'Dracula',
 'County Dracula (Fictitious Character)',
 'Count Dracula (Fictional Character)',
 'Count (Fictitious Character)',
 'Bram)',
 'Trilogy',
 'Bram',
 '1847-1912',
 '18.05 English Literature',
 'Ética',
 "Women'S And Gender Studies",
 'Women Private Investigators',
 'Woman',
 'Verschwinden',
 'Upper Class',
 'Magie',
 'Lyra Belacqua (Fictitious Character)',
 'United States Studies',
 'Das Bo\x98Se',
 'Mystery & Detective Fiction',
 'New List 20120630',
 'Battles',
 'Personas Casadas',
 'Secrets',
 'Victims Of Crimes',
 'The Inheritance Cycle',
 'Wives',
 'American Authors',
 'Inheritance - The Inheritance Cycle',
 'Biographies As Topic',
 'Tempérament',
 'Temperament',
 'Biography As Topic',
 'Psychological Introversion',
 'Psychological Extraversion',
 'Personality',
 'Large Print Type Books',
 'Introverts',
 'Introversion (Psychology)',
 'Ca',
 'Fiction / Thrillers',
 'Fiction / Suspense',
 'West Virginia',
 'Fiction / Mystery & Detective / General',
 'Zuo Pin Ji',
 'Manners And Customs',
 'Duan Pian Xiao Shuo',
 'Novelas Juvenil',
 'Novela Fantástica Estadounidense',
 'Cuentos De Amor',
 'Adolescentes',
 'Japan',
 "Youth'S Writings",
 'Vietnamese Language',
 'Viaje',
 'Ma\x98Nnliche Jugend',
 'Kampf',
 'American Detective And Mystery Stories',
 'Crimes Against',
 'Escritos De Adolescentes',
 'Desaparecidos',
 'Detective And Mystery Fiction',
 'Diaries',
 'Esposas Maltratadas',
 'Esposos',
 'Introversion',
 'Healing Power Of Nature',
 'Extraversion (Psychology)',
 'Extraversion',
 'Married People--Psychology',
 'Married People -- Psychology',
 'Aspects Psychologiques',
 'Marriage--Psychology',
 'Besluitvorming',
 'Mariage',
 'Bf 448 G543 2007',
 'Hq734 .G7136 1999',
 'Hq 734 G686 1999',
 'Couples Mariés',
 'Comunicación En El Matrimonio',
 'Communication In Marriage',
 'Bf448 .G53 2007',
 'Communication',
 '306.81',
 'Social Science / Sociology',
 'Psychology / Social Psychology',
 'Empathy',
 'Cognitive Psychology & Cognition',
 'Compassion',
 'Decisiones',
 'Matrimonio',
 'Matrimonios',
 '153.4/4',
 'Or',
 'Ecology',
 'Award:Hugo Award=1966',
 'Science-Fiction Ame Ricaine',
 'Roman Ame Ricain',
 'Dune (Lugar Imaginario)',
 'Hi',
 'Littérature Fantastique',
 'Nv',
 'Français (Langue)',
 'Pacific (Ak',
 'Political Science / Public Policy / Cultural Policy',
 'Angela',
 'Spouses',
 'Social Science / Popular Culture',
 'Social Science / Anthropology / Cultural',
 'Pacific Crest Trail',
 'Relations Entre Hommes Et Femmes',
 'Self-Actualization (Psychology) In Women',
 'Wa)',
 'Psicología',
 'Das Böse',
 'Dwarves',
 'Fairy Tales & Folklore - General',
 'Amitie',
 'Figure Skaters',
 'Figure Skating',
 'Officiating',
 'Skating',
 'Sports Stories',
 'Tournaments',
 'Ethnic Conflict',
 'Fiction / Cultural Heritage',
 'Sinhalese (Sri Lankan People)',
 'Sri Lanka',
 'Tamil (Indic People)',
 'Children: Grades 4-6',
 "Children'S Books - Young Adult Fiction",
 "Children'S Books - Young Adult",
 "Children'S 12-Up - Fiction - Fantasy",
 'Children And Adults',
 'Carnegie Medal',
 'Belacqua',
 'Artic Regions',
 'Arctic Regions -- Juvenile Fiction',
 'Arctic Regions -- Fiction',
 'Children: Young Adult (Gr. 10-12)',
 'Children: Young Adult (Gr. 7-9)',
 'Dämon',
 'Kidnapping',
 'Lyra (Personaje Literario)',
 'Lyra (Fictitious Character) -- Juvenile Fiction',
 'Lyra (Fictitious Character)',
 'Lugares Imaginarios',
 'Ws 105.5.F2 W215G 2005',
 'Livres En Gros Caractères',
 'Kind',
 'Kidnapping -- Juvenile Fiction',
 'Kidnapping -- Fiction',
 'Juvenile Fiction -- Social Themes -- Self-Esteem & Self-Reliance',
 'Enlevement',
 'Juvenile Fiction -- Fantasy & Magic',
 'Radioactive Pollution',
 'Imaginärer Schauplatz',
 'Great Britain',
 'Fiction - General',
 'Études De',
 'Familiars (Spirits)',
 'Experimentos',
 'Entführung',
 'Arctic Regions',
 'Granddaughters',
 'Chinos',
 'Action & Adventure - General',
 'Blind',
 'Berliner Mauer',
 '18.06 Anglo-American Literature',
 'Special Interest',
 'Automobile Racing Drivers',
 'Dog Owners',
 'Computer Viruses',
 'Écrits De Jeunes',
 'Spanish: Grades 3-4',
 'Dogs',
 'Literature & Fiction -- World Literature -- United States',
 'Phantastische Erzählung',
 'Männliche Jugend',
 'Juvenile Fantasy',
 "Heather'S Pick",
 'Pets',
 'Fighting',
 'Fiction - Science Fiction',
 'Fiction - Fantasy',
 'Chinese',
 'Fairy Tales & Folklore - Single Title',
 'Ciegos',
 'Enfants Aveugles',
 'Cycling',
 'Nebraska',
 'Youth',
 'World War (1939-1945) Fast (Ocolc)Fst01180924',
 'Tweede Wereldoorlog',
 'Portuguese Language Materials',
 'Personnes Aveugles',
 'People With Disabilities',
 'Grandmothers',
 'Juventud',
 'Jeunesse',
 'Sagas',
 'Bicycle Touring',
 'Guerra Mundial Ii',
 'Germany',
 'German Occupation Of France (1940-1945) Fast (Ocolc)Fst01353176',
 'Problem Solving',
 'France',
 'Fiction / Historical',
 'Fiction / General',
 'America',
 'Enfants Et Guerre',
 'Juvenile Fiction -- Action & Adventure',
 'Homer.\x1e 4',
 'Propaganda',
 'Physiopathology',
 'Fiction / Humorous / General',
 'Climate',
 'Wojna',
 'Vie Urbaine',
 'Princesses',
 'Klątwa',
 'Bénédiction Et Malédiction',
 'État De Stress Post-Traumatique',
 'Treatment',
 'Traumatisme Psychique',
 'Trauma Survivors',
 'Traitement',
 'Therapy',
 'Therapie',
 'Stress Disorders',
 'Sexual Trauma',
 'Sexual Abuse',
 'Psychotherapie',
 'Psychisches Trauma',
 'Psychic Trauma',
 'Posttraumatisches Stresssyndrom',
 'Post-Traumatic Stress Disorder (Ptsd)',
 'Post-Traumatic Stress Disorder',
 'Fiction / Satire',
 'Maladies À Virus',
 'Plague',
 'Ps3552.U827 P37 2000',
 'Contrãole (Psychologie',
 'Control (Philosophy)',
 'Ambição',
 'Abridged Audio - Misc. Nonfiction',
 'Monastic And Religious Life',
 'Hinduism',
 'Happiness',
 'Doctrines',
 'Twenty-First Century--Fiction',
 'Twenty-First Century',
 'Faith',
 'Resilience (Personality Trait)',
 'Environmental Disasters',
 'Comics & Graphic Novels / Science Fiction',
 'Comics & Graphic Novels / Historical Fiction',
 'Black Teenage Girls',
 'Apocalyptic & Post-Apocalyptic',
 'African Americans--Fiction',
 'African American Women',
 '813/.54',
 'Virus Diseases',
 'Résilience (Trait De Personnalité)',
 'Post-Traumatic',
 'Physical Violence Recovery',
 'Contrôle (Psychologie.)',
 'Neurowissenschaften',
 'Attitude Change',
 'Accounting',
 'Vol Spatial',
 'Space Flight',
 'Memory Disorders',
 'Hard Science-Fiction',
 'Hard Sci-Fi',
 'Fin Du Monde',
 'Fiction / Science Fiction / Action & Adventure',
 'Astronauts',
 'Astronautes',
 'Transitional Objects (Psychology)',
 'Réalisation De Soi',
 'Pérdida (Psicología)',
 'Pintores',
 'Perte (Psychologie)',
 'Jóvenes (Varones)',
 'Jeunes Hommes',
 'Goldfinch',
 'Auto-Realización',
 'Artistes',
 'Artistas',
 'Art',
 'Consumption (Economics)',
 'Financial Literacy',
 'Investing',
 'Clinical Medicine',
 'Neuroscience',
 'Neuroplasticity',
 'Neurology',
 'Mind And Body',
 'Mental Health',
 'Medical',
 'Körpererfahrung',
 'Health & Fitness',
 'Evidence-Based Medicine',
 'Combat',
 'Brain',
 'Management',
 'Addiction',
 'Abuse',
 'Wealth',
 'Self-Help Techniques',
 'Satisfaction',

In [47]:
drop_mask = df[df['Category'].isin(to_remove)]

In [57]:
df.drop(drop_mask.index, axis=0)

      Unnamed: 0   Book Id                 Category
3              3  58416952             High Fantasy
8              8  22878967                  Fantasy
9              9  22878967          Fantasy Fiction
13            13  37640636       Action & Adventure
14            14  37640636                  Fantasy
...          ...       ...                      ...
3755        3755  39863488                Thrillers
3757        3757  43848929          Conduct Of Life
3759        3759  43848929  Interpersonal Relations
3764        3764  43848929        Social Psychology
3765        3765  43848929           Social Science

[1594 rows x 3 columns]

In [58]:
df = df.drop(drop_mask.index, axis=0)

In [59]:
lib.export_data(export_categories_path, df)

PortfolioLogger.lib.tools: INFO: Exporting 4782 elements (0.13 MB) to /Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/goodreads/clean/my_books_categories_CLEAN_CLEAN.csv
PortfolioLogger.lib.performance: INFO: <function export_data at 0x10d436ac0> took 0.006 secs to complete.

PosixPath('/Users/christophermagno/PycharmProjects/MagnoDataAnalystPortfolio/datasets/goodreads/clean/my_books_categories_CLEAN_CLEAN.csv')